### ISSUE TITLE
Vmix shortcut recall

### ISSUE THREAD

**Issue by willosof** [bitfocus/companion-module-studiocoast-vmix#1]
_From @Guillemete on September 22, 2018 14:42_

**Describe the feature**
Recall shorcuts in Vmix. 

**Is this platform dependent (windows, mac, ..)?**

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
In vmix, you can create shortcuts to star/stop timer, advance PPT, change the timer countdwon "live", change an aux output. Would be handy to simply recall directly from the stream deck

_Copied from original issue: bitfocus/companion#253_

**Comment by JeffreyDavidsz** [comment]
@Guillemete seems you would like to have the shorcutted functions directly selectable as an option in companion? Which functions would you need beside start/stop timer, advance PPT, change the timer countdown "live", change an aux output?
Other option is to have a listener sending hotkeys to the active vMix window, but we prefer to program in the module what users use most often. Let me know!

**Comment by McHauge** [comment]
gonna close this, since I don't see how this would bee done, or how this would be practical. feel free to open it up again if need be.
