### ISSUE TITLE
VMix Tally Feature Not working correctly when input is changed via Companion Button

### ISSUE THREAD

**Issue by elmills** [bitfocus/companion-module-studiocoast-vmix#10]
This is related to the testing for Tally/Feedback feature added

 Issue #5 .

I have been testing with Alpha 2.0 build companion-2.0.0-e67b21f-1708-win64
Vmix Module studiocoast-vmix@1.1.2: StudioCoast:vMix by Per Røine

I can provide additional logs as necessary, but I have 3 inputs setup for testing.  Input 1/2/3 with both Live and Preview.
![2019-08-19 17_19_07-Bitfocus Companion - Admin](https://user-images.githubusercontent.com/9019827/63300151-8481c400-c2a5-11e9-8340-b447add5eb21.png)

When I select the Preview/Live it work in Vmix in all scenarios, but here are the use cases:

- via the Vmix software the input/preview tally status  updates correctly on Companion.  
- if I use the cut or fade button on Companion App the status is updated correctly on Companion
- if I use the button 20.10-12 the status is not updated correctly on the companion app.  Video recording of issue is attached, along with page config
[record_000011.zip](https://github.com/bitfocus/companion-module-studiocoast-vmix/files/3517785/record_000011.zip)
[Spinnaker_page 20_20190819-1719.zip](https://github.com/bitfocus/companion-module-studiocoast-vmix/files/3517791/Spinnaker_page.20_20190819-1719.zip)

**Comment by McHauge** [comment]
Is this still a problem with the newer builds of this module?

**Comment by elmills** [comment]
I havent had a chance to test.  I will try to test it by the end of the
week.

Everette
