### ISSUE TITLE
vmix custom commands not working in 2.2.0+

### ISSUE THREAD

**Issue by legenddan** [bitfocus/companion-module-studiocoast-vmix#100]
**Describe the bug**
See title - 2.1.2 has functional custom commands, I am trying out 2.2.0 and all by custom command buttons are non-functional. 

**To Reproduce**
make any custom command button for vmix

**Expected behaviour**
Custom commands to be executed on vMix

**Screenshots**
n/a

**System (please complete the following information):**
 - Companion Version 2.2.0 (0e1bf2a4-3169)
 - vMix version 24

**Additional context**
n/a

**Comment by McHauge** [comment]
@legenddan Hi would you mind sharing a screenshot of one or more of the custom commands, then I'll give it a look later. There have been some changes that include URI encoding and that might give some errors.

**Comment by legenddan** [comment]
Hey @McHauge Sure. Here are two of my buttons. One is a timer reset and the other is a multiview layer toggle. Both have their own built-in actions that work in 2.2.0 but not when written as custom commands. 
![Screen Shot 2021-03-22 at 9 08 40 AM](https://user-images.githubusercontent.com/81167205/111994970-cb254900-8aee-11eb-9ce9-6ab6e6a4a816.png)
![Screen Shot 2021-03-22 at 9 09 06 AM](https://user-images.githubusercontent.com/81167205/111994971-cb254900-8aee-11eb-9016-c410bd2b4ece.png)

**Comment by McHauge** [comment]
@legenddan I'll give it a look, I'm 99% sure it's because of the URI encoding, happening after the first space in the custom command.

**Comment by legenddan** [comment]
@McHauge =rockstar

**Comment by stevespaw** [comment]
My custom command is now broken in newest build:
SetVolume Input=Input2&Value=%2B%3D1
raised volume with URL encoding on the +=

Is there a new method?

**Comment by McHauge** [comment]
How new of a build @stevespaw

**Comment by McHauge** [comment]
Do you happen to have a screenshot of the command on the button

**Comment by McHauge** [comment]
You should not need the encoding in the command, it's done in the code, if you type it out it should work

**Comment by stevespaw** [comment]
This has worked perfect before in this project, I am not sure when (what version of 2.2) it stopped work, sorry.
I have tried this with just the += also , no go so far.

**Comment by McHauge** [comment]
What would the command normally be? Yes we have been swapping a bit around on no encoding, to full, to something in between.

**Comment by McHauge** [comment]
The goal was to have it work with no encoding done by the user. Because of how it works in 2.1.2 where it's though http, and now it needs encoding when sent though TCP directly in 2.2.0

**Comment by stevespaw** [comment]
Hmmm now wondering if vMix update broke this:
http://localhost:8088/api/?function=SetVolume&Input=Input1&Value=+5
Function completed, but nothing happens.
??

**Comment by McHauge** [comment]
Well, not sure, did not expect that you could even do that in the first place 😅 would have thought that you would need to know that the current volume is and pass that back with the 5 added. But if it did before, well, you could try and go back to 2.1.2 and see if it worked there or a version back in vmix

**Comment by stevespaw** [comment]
OK so:
http://localhost:8088/api/?Function=SetVolume&Input=1&Value=-=5 works perfect.
http://localhost:8088/api/?Function=SetVolume&Input=1&Value=+=5 does not !  This leads me to where I was with this last year.
[https://forums.vmix.com/posts/t14323-shortcut-to-increase-decrease-volume-in-increments](url) start with post  8 ( right example, but has a typo 2B not 20 as shown) the + only works when encoded. 
http://localhost:8088/api/?Function=SetVolume&Input=1&Value=%2B%3D5 works from the browser  !!!
http://localhost:8088/api/?Function=SetVolume&Input=1&Value=+=D5  does not !!!

**Comment by McHauge** [comment]
That would certainly be possible yes, but please make it it's own issue, that way it's simpler to keep track of

**Comment by stevespaw** [comment]
Ok I can do that, but we discovered a work around. since the - works, we use a negative number for +
i.e. Function=SetVolume&Input=1&Value=-=-5 
is the same as +5.  this works :-)
