### ISSUE TITLE
Feedback for recording doesn't change the colour of the button

### ISSUE THREAD

**Issue by frankleggett** [bitfocus/companion-module-studiocoast-vmix#102]
**Describe the bug**
The Toggle Rec doesn't change the colour of the Streamdeck button

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
The streamdeck button background should turn Red when recording

**Screenshots**

**System (please complete the following information):**
 - Companion Version [e.g. 2.1.1 (f74294d-2656)]
 - vMix version [e.g. v24]

**Additional context**

**Comment by McHauge** [comment]
@frankleggett would you mind testing this in the newest 2.2.0 beta, mine worked yesterday :)

**Comment by frankleggett** [comment]
Will do next week, I’m doing a gig at the moment so I don’t want to change anything.

 

The other thing to note is that I am using a 6 button Streamdeck and my 15 button Streamdeck was OK last week.
