### ISSUE TITLE
Clocks variable

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-studiocoast-vmix#103]
**Describe the feature**
It would be extremely helpful to be able to display Record (and Stream time etc) time from the vMix clocks as a variable on a button

**Is this version dependent (vMix v24.)?**
Don't think so.

**If documentation is required to implement, do you know where to find it?**

**Usecases**
We do remote recording and it would be great to be able to see the recording time on the Deck rather than having to screen share just to see timing.

Thanks!

**Comment by McHauge** [comment]
@obcocav I'll have to look at what is available in the API, but no matter what, the precision of this will depend on what polling rate you set in the instance, since this is not something that is supported in activators, just like with video timers.

Just to make sure you are talking about the "production clock" or just the general amount of time you have streamed/recorded so far?

**Comment by obcocav** [comment]
The main thing I'm looking for is the amount of time recorded.  Right now we get display that via the production clock going to an output.  Record time is what I'm looking for though so if there is another method I don't think it would matter.  

Thanks!

**Comment by McHauge** [comment]
I'll give it a look

**Comment by McHauge** [comment]
@obcocav I think I got the variables working, they will be included in the next pull into the v2.2.0 betas :)

![image](https://user-images.githubusercontent.com/31018035/115229897-e1d1b680-a113-11eb-92d4-0dbbc8f21587.png)

**Comment by obcocav** [comment]
Y’all are awesome!  Thank you so much!

**Comment by McHauge** [comment]
Closing this as it's now a part of the 2.2.0 betas

**Comment by jmrowe504** [comment]
So I have tried this clock and I am only able to get my recording clock. Is there a method to get the streaming clock? I do both stream and record but they start about half and hour apart and this would help me greatly.
