### ISSUE TITLE
Layer Tally indicators don't work with new(ish) companion feature that removes the top bars from buttons

### ISSUE THREAD

**Issue by empyfree** [bitfocus/companion-module-studiocoast-vmix#105]
The layer tally indicator feedback system seems to be broken if you choose to hide all the top bars from buttons. With that option un-ticked the indicators work as I anticipated, with it ticked I get no useful feedback, and a strange holdover of full button feedback if I go from a simple input (feedback if previewed for example) to another input that uses the first one on a layer. This is hard to explain in words!

**Comment by McHauge** [comment]
Correct just tested this too, definitely a bug, this is what it shows in the log: 
![image](https://user-images.githubusercontent.com/31018035/116365694-ca768580-a805-11eb-95cf-b16fd99acc2a.png)

also if the corner is turned on and you then remove the topbar, Companion will crash.

**Comment by McHauge** [comment]
@krocheck I think this might be a core bug, or at least a part of it might be, with the indicator stuff

**Comment by krocheck** [comment]
Its sort of a core bug, but will need to be fixed here.  We did a `new Image()` which takes the default of 72x58.  I can't put detection into `Image` because it doesn't have `system` to query the config.  So it'll need to get fixed here ... shure-wireless is in the same boat.
