### ISSUE TITLE
X/Y Layers / Multiview Name & GUID not working

### ISSUE THREAD

**Issue by Howlswolf** [bitfocus/companion-module-studiocoast-vmix#111]
**Describe the bug**

Some Field do not work with Name & GUID, (even if its indicated it should), They do work with Input# though.

Layers / MultiView - Set Destination Input for Routable Multiview Overlay Layer
> Destination MV Input

Layers / MultiView - check selected destination input
> Input (Nr/Name/GUID) 

![Screenshot 2021-07-13 094314](https://user-images.githubusercontent.com/87432144/125639246-20da8e44-8e43-4fda-9055-cecb5414b6fd.png)

**Expected behaviour**
to work with Input#, Name & GUID

**System (please complete the following information):**

- Companion Version: companion-2.2.0-92a53337-3474-win64
- vMix version: 24.0.0.63

**Additional context**
Forced to use vMix Dynamic's instead of this nice module, Input# are just not reliable enough since they can be easily changed just by a miss click...

**Comment by jordinordbeck** [comment]
This is a very worrying bug because if you move or eliminate inputs with an earlier number in the vMix preset , those actions will stop working fine.
