### ISSUE TITLE
parentheses in vMix input names are eliminated from the $(vmix:input_X_name) variable value in vMix-Companion module

### ISSUE THREAD

**Issue by jordinordbeck** [bitfocus/companion-module-studiocoast-vmix#112]
Parentheses in vMix input names are eliminated from the $(vmix:input_X_name) variable value in vMix-Companion module.
So, in case you want to use the value of the variable of an input whose name contains parentheses you will not get the right name. As an example, vMix automatically creates a name with parentheses when selecting an NDI output as an input.

**Comment by thedist** [comment]
Because Companion v3 has stricter limitations of variable names, it would be difficult to add parentheses to the variable name, but for variable values I'm not currently seeing any issue with parentheses being in variable values, including for input names.
