### ISSUE TITLE
VMIX Stream Key 

### ISSUE THREAD

**Issue by eleftheriakodikas** [bitfocus/companion-module-studiocoast-vmix#113]
Ability to paste Stream Key from another computer, The command `StreamingSetKey Value: xxxx` only works on the First tab (1 of 3) on the stream setting. If there's a feature to target each tab and paste the stream key that would be nice.

Documentation: https://util.dist.dev/vmixapi

**Usecases**
Ability to paste streamkey on another VMIX computer quickly

![vmix stream](https://user-images.githubusercontent.com/71998285/126734189-f0e48783-d400-4f9b-bfce-b6c10270e1a1.png)

**Comment by thedist** [comment]
Unfortunately this can't be implemented until vMix provides us the functionality to select which stream to set the stream key of.
