### ISSUE TITLE
List / Slides name list

### ISSUE THREAD

**Issue by mtregael** [bitfocus/companion-module-studiocoast-vmix#115]
**Describe the feature**
Get the list of file names available in List and Slides.

**Is this version dependent (vMix v24.)?**
Not sure

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc., to help the developers along.

**Usecases**
In companion, it should be possible to have dynamic buttons using feedback.
By creating a button using a sort of variable like: "`$(vmix:input_[GID]_index_[id]_name)`" it should be possible to get the file name.
Actually, it is only possible to retriever selected name.

**Comment by mtregael** [comment]
No, i know that feedback function. It show the name of the SELECTED list element only. 
In my case i want to show the name of a specific index.
So, that will allow me to have a page with many buttons, different index and it show the index associated name instead of having them hard coded in the name of the button.
In the feedback "vmix: Slides/List - QShow Selected Slide/Index Name", it should have a "Selected index" field where i can put the index I want to display name. If the field is empty, it show the Selected index.

**Comment by Howlswolf** [comment]
Oh, sorry I read too quickly :) , I could actually use something like that. I have a page with Musics from a list, it would be nice to have the name of each song on each buttons automatically. 

I know they are working on a big update with alot of new variables... hopefully its gona be in that one  :)

**Comment by mtregael** [comment]
Yes it's exactly what i want. It was not so easy to explain. :)
In my case, it's for video transistions. But, it should be the same for music video clips.

**Comment by Howlswolf** [comment]
I use name primarily for programing ... I never use nr, its not safe enough, some inputs could be move by mistake... and I would use GUID only when I need to pull the name with a Variables.

**Comment by mtregael** [comment]
I always use GUID that is unique and safe.

In the api of vmix, the file list is always available:
`<input key="926c7070-cd4e-42b8-a43a-b66829131754" number="6" type="VideoList" title="List - SavedScreen1.png" shortTitle="List" state="Paused" position="0" duration="0" loop="False" muted="True" volume="100" balance="0" solo="False" audiobusses="M" meterF1="0" meterF2="0" gainDb="0" selectedIndex="1">
List - SavedScreen1.png
<list>
<item selected="true">C:\Users\xxx\Documents\SavedScreen1.png</item>
<item>C:\Users\xxx\Documents\SavedScreen0.png</item>
<item>C:\Users\xxx\Documents\SavedScreen5.png</item>
<item>C:\Users\xxx\Documents\SavedScreen4.png</item>
<item>C:\Users\xxx\Documents\SavedScreen3.png</item>
<item>C:\Users\xxx\Documents\SavedScreen2.png</item>
</list>
</input>`

So i think it should be possible to retrive the complete list as the selected one is  already available...

**Comment by McHauge** [comment]
It's not if it possible, it how to do it so you won't be to over overwhelmed when you have 100-200 videos in a list, them because vmix has 3 different types of users you need to add all 3 types (nr, name and guid).

Also think a bout having more that one of these lists, the variables tab becomes very long. This is one of those things where i thing a "feedback" is better where you define an input and an index. And appends the indexed video to the button text

**Comment by McHauge** [comment]
Also guid is not safe in my mind, if i by accident delete an input, I can't add it again, without having to redo all my buttons, with the name i can just rename it and I'll be back where I were before

**Comment by Howlswolf** [comment]
I think McHauge is on the right track about the feedback, the only thing we need is to have the name of a certain list item displayed on a button... so its not the variable that is needed.  Something like this: 

Feedback : List Name    ; Input:(nr,name,guid)     ; List Item number: (1...)

it would return the name of what is in position 1 etc .... now we will have to be carefull not to mess the order of our clips ;)
