### ISSUE TITLE
Feedback Overlay-Overlay status : Foreground Color issue

### ISSUE THREAD

**Issue by Howlswolf** [bitfocus/companion-module-studiocoast-vmix#117]
**Feedback Overlay-Overlay status**
Changes in this function is creating Foreground color not to work correctly.

The Foreground color is now linked between the Preview and Program. And it changes the Foreground color if its either on Preview or Program when like in the attached image you use 1 button for preview and another one for program.

![BadOverlayColor](https://user-images.githubusercontent.com/87432144/128408899-6c4905d3-57bf-4cf4-817f-0d9d8c985192.jpg)

To fix this maybe have a drop down to choose what the feedback will be affected by: Preview / Program / Preview+Program like I have seen on other feedback functions.

Companion Version: companion-2.2.0-92a53337-3474-win64
vMix version: 24.0.0.63

**Comment by McHauge** [comment]
If i remember correctly, this is not possible with the current vmix Api, as it only provides if it's on, not if it on preview, program, off. But only a yes it's in use, or no it's not in use.

But if you can find a way to tell them apart in the Api, please let us know, otherwise you would have to ask vmix to make that info available first 😊

**Comment by Howlswolf** [comment]
I though in the past it was acting different but I had the same foreground color on both...my bad. 

Looking at the API it does indicate when it is on preview. 
not active = overlay number="1"/>
on program = overlay number="1">22</overlay>
on preview =  overlay number="1" preview="True">22</overlay>

Im not a programmor, but I think there might be something that can be done with this info... 

Thanks for all the work you do McHauge, really appreciated

**Comment by Howlswolf** [comment]
This might be less confusing :) 

```<vmix>
<version>24.0.0.63</version>
<edition>4K</edition>
<inputs>
<input key="8c1bedd3-378a-4dfd-a940-4d185c36e271" number="1" type="Colour" title="Colour Bars" shortTitle="Colour Bars" state="Paused" position="0" duration="0" loop="False">Colour Bars</input>
<input key="2c58a211-27ef-4d29-999e-3b963b275af3" number="2" type="Colour" title="Colour" shortTitle="Colour" state="Paused" position="0" duration="0" loop="False">Colour</input>
<input key="3245c7d9-aa46-4761-b000-694c5ed049d6" number="3" type="Colour" title="Colour" shortTitle="Colour" state="Paused" position="0" duration="0" loop="False">Colour</input>
<input key="d8cf9657-55f3-4d8b-b82c-5be5b0d2005c" number="4" type="Colour" title="Colour" shortTitle="Colour" state="Paused" position="0" duration="0" loop="False">Colour</input>
</inputs>
<overlays>
<overlay number="1"/>
<overlay number="2">3</overlay>
<overlay number="3" preview="True">4</overlay>
<overlay number="4"/>
<overlay number="5"/>
<overlay number="6"/>
<overlay number="7"/>
<overlay number="8"/>
</overlays>
<preview>2</preview>
<active>1</active>
<fadeToBlack>False</fadeToBlack>
<transitions>
<transition number="1" effect="Fade" duration="500"/>
<transition number="2" effect="Merge" duration="500"/>
<transition number="3" effect="Wipe" duration="500"/>
<transition number="4" effect="CubeZoom" duration="500"/>
</transitions>
<recording>False</recording>
<external>False</external>
<streaming>False</streaming>
<playList>False</playList>
<multiCorder>False</multiCorder>
<fullscreen>False</fullscreen>
<audio>
<master volume="100" muted="False" meterF1="0" meterF2="0" headphonesVolume="100"/>
<busA volume="100" muted="False" meterF1="0" meterF2="0"/>
</audio>
<dynamic>
<input1/>
<input2/>
<input3/>
<input4/>
<value1/>
<value2/>
<value3/>
<value4/>
</dynamic>
</vmix>```
