### ISSUE TITLE
Feedback from Input NAME does not work in latest Beta

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-studiocoast-vmix#118]
**Describe the bug**
Using the latest beta of Companion 2.2.0 today the feedback from an input name no longer works at all.  Feedback works as expected when using an input number.

**To Reproduce**
1.  Add feedback to a button by an input name.  Doesnt work.
2. 
**Expected behaviour**
Worked well in previous version linking feedback to name EX. "CAM 1" vs Input "1"

**Comment by Howlswolf** [comment]
McHauge has fixed it, its just waiting to be pulled in the beta.
