### ISSUE TITLE
Allow for DynamicX or Custom Variables to be used in vMix custom commands

### ISSUE THREAD

**Issue by rgrtnlst** [bitfocus/companion-module-studiocoast-vmix#119]
**Description of feature request**
When sending commands from Companion to vMix the variables _Dynamic1_ through _Dynamic4_ can be used to affect specific layers/values/texts without the need to create duplicate sets of buttons. However: This is not possible when sending custom commands in plain text using _vMix: Run custom command_
The same is true for the Companion-internal custom cariables e.g. $(internal:custom_variable_name)

**Is this version dependent (vMix v24.)?**
Using _vMix: Run custom command_: Not dependant on version.
Using vMix's _DynamicX_ : requires a version with cynamic variables implemented.

**If documentation is required to implement, do you know where to find it?**
If it is implemented on the Companion end, the feature should be "easy" to add. However, I am not certain the vMix API can handle a request should the solution rely on _DynamicX_.

**Usecases**
I have an overlay graphic in Vmix with multiple graphical elements. It is a scoreboard for team sports and I want to show/hide different image elements (using _SetImageVisible_) for the home team as well as the guests. 

Currently I am restricted to the two following solutions:
- Split the elements into standalone Inputs, which is more difficult to line up properly.
- Create duplicate (or more) buttons in Companion which takes up more real easte.

**Sidenote**
An entirely different request would be to implement _SetImageVisible_ as a function similar to _vMix: vmix: Title - Adjust title text_  where there is an option to pass _SelectedIndex_ as a variable in an input field.

**Comment by McHauge** [comment]
@rgrtnlst did you check this in the latest beta's, about 3 weeks ago, I added support for using all internal variables in companion as values inside all text fields in actions and feedback? So I think this is already possible in the newest 2.2.0 betas

**Comment by rgrtnlst** [comment]
I'm running the beta 2.2.0 (2.2.0-11961d9d-3530)

It works in separate text fields. As an example: I can send both Companion-internal variables in _vmix: Title - Adjust title text_. The specific problem is when I try to add either a variable or a vMix DynamicX as _part of_ a custom command.

The following command works
SetImageVisible Input=7&SelectedIndex=3

The following command does not work
SetImageVisible Input=7&SelectedIndex=Dynamic1 (or rather it deafults to 0)

The following setup works
![For_Github_vMIx](https://user-images.githubusercontent.com/16123532/132994561-ca109863-1ec8-43be-9d2c-2c99cb2c8ce5.png)

**Comment by McHauge** [comment]
That's not a companion variable, that's a vmix internal variable, not totally sure how those are supposed to work via the API.


I was talking about Companion variables, the one starting with $(some instance:some name), those are supported, and you can create custom versions of them with custom values

**Comment by rgrtnlst** [comment]
@McHauge 
Thank you so much for taking the time. I can confirm that the vMix variables works (as shown in the image above), so good work!

I get the same issues with Companion variables.

This works
`SetText Value=98&Input=7&SelectedIndex=2`

This does not work (or rather it sets the text explicitly to _$(internal:custom_variable_name)_ parenthesis and all)
`SetText Value=$(internal:custom_variable_name)&Input=7&SelectedIndex=2`

Note: The chosen function above is only for testing, I am aware they are possible to execute with a dedicated command. I get the same issue with the command I am working on: _SetImageVisible_

**Comment by McHauge** [comment]
@rgrtnlst I'll have to check, but you might actually be right about it not working inside the custom command. as that is handled a bit different from the others, due to others being encoded, and the custom just being a raw one to one with what you type

**Comment by rgrtnlst** [comment]
@McHauge as far as I can tell from the code, in _actions.js_ I see that you check for a custom variable in the action's option. Line 1413:

`	// if an option includes a variable, get it's value and replace the name for the actual value
		if (String(action.options[property]).includes('$(')) {`

But as you stated: I cannot see a corresponding check with the custom command. Line 1447 (?)

**Comment by McHauge** [comment]
yes but the "custom commands" is not part of the "normal" format for where it get's it's values

as you can see on the link below, it get's its value directly from the text field, not from the parshed values.

https://github.com/bitfocus/companion-module-studiocoast-vmix/blob/6e96cf41e83298c8abb39efbb0a0f16ced31d1b1/src/actions.js#L1441-L1447

**Comment by guimacjr** [comment]
I'm testing some stuff with variables and making a instance feedback with a variable works, but, it seems that the variable only update when the feedback has the variable written, after adding it, if I change what is on the variable, it wont update the feedback.

![image](https://user-images.githubusercontent.com/97537189/148971842-a2ecf4b2-c6ec-4485-a92f-a620f85c9fde.png)
This is what I'm using and I'm changing what is on the variable, but, it isn't checking the other input number.
