### ISSUE TITLE
Companion does not work via VPN

### ISSUE THREAD

**Issue by RoboraceMedia** [bitfocus/companion-module-studiocoast-vmix#120]
Hello! 

We're building remote audio video production and would like to use  BitFocus Companion and Elgato StremDeck for remote control of vMIx instance. 

To clarify the environment:
1. remote studio (where vMix operator is located) is in Moscow, Russia
2. vMix instance which is switching and streaming node is located in LA, US
3. vMix Studio is used to control remote vMix

What is happening:
1. the connection between remote studio Companion and remote vMix is establishing successfully via VPN by Perimeter81
2. the commands from either Companion Emulator or from Elgato installed in remote Studio are being sent (we can see packets in network when pressing buttons)
3. vMmix is not reacting — no inputs switching, or audio bus switching

The same setup being local, i.e. in one Physical Network is working perfectly.

What can be wrong in our configuration? 

For sure we can use remote USB ports publishing and mapping, but the scenario with VPN usage is the most preferable for us and looks logical.

**Comment by thedist** [comment]
Closed for inactivity. It appeared to be a configuration/connectivity issue rather than a bug.
