### ISSUE TITLE
Instance Status for Output Source

### ISSUE THREAD

**Issue by lestrobl** [bitfocus/companion-module-studiocoast-vmix#124]
**Describe the feature**
I want to have an instance status or variable for the output source to make the "routing" of an input directly to an output visible.
Like the "Change colors on live input" - but directly with the outputs: "Change colors on output source"

**Is this version dependent (vMix v24.)?**
No

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc., to help the developers along.
No

**Usecases**
Add a couple of use cases for why this should be implemented and when/why to use it.
Using the Output as a classic cut bus (like an old videorouter) and show visible, which input is outputted.

**Comment by McHauge** [comment]
Hello, I think i understand what you want, and you're not the first, but the vMix API does sadly not allow us to have feedback on that is sent to an output.

The only way to get that would be to set output 1-4 = mix 1-4, as mixes are the only "output type" that supports feedback via the API
