### ISSUE TITLE
Ad Replay Functions to vMix

### ISSUE THREAD

**Issue by peteraellig** [bitfocus/companion-module-studiocoast-vmix#125]
please add the replay functions
-Play Event
-Play Selected Event
-Play All Events  
you only have the Option "to output", without this option, you could test a playlist to preview, without going onair....

please add the toggle function for the overlay
-overlay 1-4 toggle

**Comment by thedist** [comment]
What version of Companion are you using, because some of that functionality has been in place for a long time already. If you're running 2.1.x then that would explain why because that hasn't been updated in over a year I believe and you'd need to move to 2.2.0

**Comment by peteraellig** [comment]
Sorry, i already found this out . Works great!
Best
Peter

Am 10.12.2021 um 12:18 schrieb Jeff Martin ***@***.***>:

﻿
What version of Companion are you using, because some of that functionality has been in place for a long time already. If you're running 2.1.x then that would explain why because that hasn't been updated in over a year I believe and you'd need to move to 2.2.0

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
