### ISSUE TITLE
Custom Command: position controls - negative relative values work, positive values don't.

### ISSUE THREAD

**Issue by David-in-Philly** [bitfocus/companion-module-studiocoast-vmix#127]
**Describe the bug**

Tried sending the following custom command to VMix:
SetPanX Preview&Value=-=0.001
This works. Also the matching shortcut using the "SetPanX" function works.

Tried sending the following custom command to VMix:
SetPanX Preview&Value=+=0.001
This doesn't work. The matching shortcut using the "SetPanX" function works

The custom commands "SetZoom" and "SetPanY" exhibit the same malfunctions.

**To Reproduce**

(See above)

**Expected behaviour**
Relative movement in the direction specified by the value specified.

**Screenshots**

- Companion Version: 2.1.3 (6b6820cd-2696)
- vMix version: 24.0.0.72

**Additional context**

**Comment by thedist** [comment]
A solution is to URL encode the special characters. So for example `SetPanX Preview&Value=%2B%3D0.001` should work. In an upcoming version we'll have an easier way to handle this use case.

It's worth noting that your companion version is quite out of date, 2.1.3 hasn't been worked on in around 2 years, it's highly recommended you switch to a 2.2.0 build.

**Comment by David-in-Philly** [comment]
Thanks!

**Comment by David-in-Philly** [comment]
I tried installing v 2.2 (win) and Companion wouldn't connect to VMix or Streamdeck. I went back to v. 2.1.4 (b03d4f0f-2714) and everything is fine again.
