### ISSUE TITLE
[BUG] Vmix Feedback active input freezes

### ISSUE THREAD

**Issue by sonicnick** [bitfocus/companion-module-studiocoast-vmix#128]
**Describe the bug**
Feedback action of background colour change for VMIX Active Input does not update button state after several  state changes 
**To Reproduce**
Buttons with action to select inputs 1-4
1. set keydown action to:
vmix: Transition - Send Input to Program (input 1)
2. Add feedback:
vmix: Live - Change colours based on live input  (input 1)
repeat for four inputs

3. Switch to taste, feedback works for 4 or 5 switch actions. 

Background colour freezes on one of the buttons (randomly) then feedback action stops updating, though the button press action continues to work.

**Expected behavior**
The feedback should reflect active input as expected

**Desktop (please complete the following information):**
- OS: Mac OS X Monterey 12.0.1
- Browser Chrome
- Companion Version 
2.2.0 (2.2.0-984ba735-3711)

**Comment by thedist** [comment]
Unable to reproduce. I'll reopen if it's still an issue for you in the upcoming version.
