### ISSUE TITLE
[Feature Request] vMix display timer/score information within Companion

### ISSUE THREAD

**Issue by Quinton-m** [bitfocus/companion-module-studiocoast-vmix#13]
**Describe the feature**
I contacted the developer of vmix to see if it would be possible to display information like times/scores etc within companion, the reply was .."As for Companion, that would be up to them to add as they do all the integration themselves."
vMix has a lot of very good API controls built in that allows you to fully control the software using 
http Generic module, for example if I set up a timer and I wanted to pause/start that timer I would simply add localhost:8088/api/?Function=PauseCountdown&Input=1
To add +1 to a score it would be 
localhost:8088/api/?Function=SetText&Input=1&SelectedIndex=0&Value=%2b%3d1            (value being +1 in ASCII URL Encoding in example above) 
SelectedIndex 0 being able to control the "clock" in this example, as its 0,1,2 etc for (clock,home,away etc)

![scoreboard](https://user-images.githubusercontent.com/54707231/64013080-f6b09f00-cb16-11e9-890b-653b20c34d54.png)

I came across Iris Countdown Timer and noticed that they implemented variables to have the timer actually be displayed within companion by changing the "button text" to a variable, and being able to have the same feature with vmix would be a really great feature, as then I could see within companion that I have added +1 to a score, or I have paused/started the clock etc as when you are connected remotely from a phone, you are not certain that you clicked the button correctly without having to look at it in vmix, you would be certain if you seen it in the emulator. (Below is a screenshot of how Iris Countdown Timer has implemented it)

![timer2](https://user-images.githubusercontent.com/54707231/64013466-c87f8f00-cb17-11e9-8fbb-42fda290a50d.png)
![timer](https://user-images.githubusercontent.com/54707231/64013476-ce757000-cb17-11e9-8e2f-08fe0a730bea.png)

Not sure what would be required for this request to happen, but I am hoping there would be a way for companion to connect with the vmix options be able to diplay within companion. I can contact the developer again, if you require certain information to accompish this.

**Is this platform dependent (windows, mac, ..)?**
vMix is a Windows only program

**If documentation is required to implement, do you know where to find it?**
I can contact developer if further information is required

**Usecases**
vmix is a streaming software, so you could have vmix running on a computer in location A, and when you are in location B you could use your phone to completely control vmix by simply clicking a button on the companion emulator, with this extra visual button you would be certain that times/scores etc have indeed been changed.

**Comment by JayPiEs** [comment]
The Stream Deck Software from Elgato has that functions from vMix implemented and vMix will send not only timer/countdown but also previews of videos or pictures from the playlist-items linked on that button and colorchanges corresponding to the function state of the button (i.e. recording, etc.)
Perhaps that helps in implementing that features?

https://youtu.be/oPG6eq0ZiGg
