### ISSUE TITLE
Connect via hostname also instead of just IP

### ISSUE THREAD

**Issue by stevespaw** [bitfocus/companion-module-studiocoast-vmix#140]
**Describe the feature**
Connect via hostname also instead of just IP address

I am not sure of what this breaks, but I would think it would "just work" ????

**Usecases**
Deployment of our systems would be easier

**Comment by thedist** [comment]
The v2.0.0 update already allows for using hostnames instead of IP, so as soon as that gets the Okay and we merge it to master it'll be available :)

**Comment by stevespaw** [comment]
Nice! I will be on the lookout!
Thanks for your work on this project.
