### ISSUE TITLE
Instance Feedback for Input Bus Routing broken

### ISSUE THREAD

**Issue by JakeyBoyPro** [bitfocus/companion-module-studiocoast-vmix#144]
**Describe the bug**
When attempting to get feedback on when an input is routed to a certain bus (e.g call audio to master etc), the button doesn't seem to change appearance.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'Feedback'
2. Click on 'Drop down list for feedback'
3. Scroll down to 'vmix: Audio - Input Bus Routing'
4. Set input to an audio input that is on master
5. See no change in button appearance.

**Expected behaviour**
Button to change appearance depending on the set Foreground/Background Colours.

**Screenshots**
![image](https://user-images.githubusercontent.com/99300012/153098439-82d01340-a9cd-4ca1-90a9-606167ac1495.png)
![image](https://user-images.githubusercontent.com/99300012/153098593-8e42a02e-608f-48a3-86b3-f9c879db39b3.png)

**System (please complete the following information):**

- Companion Version: 2.2.0+38756d4ae191
- vMix version: 24.0.0.72 x64

**Additional context**
Before upgrading to the latest Beta build of Companion this worked perfectly fine (used it on a show I worked on 07/02/2022) but since upgrading, buttons seem to no longer change appearance with this feedback. The Preview/Program feedbacks still work fine as I've got those working. I have also tried this with each bus Master through to G and no joy.

**Comment by thedist** [comment]
This'll be fixed whenever the commit is added to the beta builds
