### ISSUE TITLE
Connect via hostname in addition to IP

### ISSUE THREAD

**Issue by shapiroconsult** [bitfocus/companion-module-studiocoast-vmix#145]
I'd love the ability to use hostname for a vMix instance instead of just the IP. For example vmix01.mydomain.com. This will allow additional flexibility in how we use the machines.

**Comment by thedist** [comment]
What version of Companion are you running, because this has been possible in the beta releases.

**Comment by shapiroconsult** [comment]
I’m using 2.1.2. Where can I find a beta that has this? I’d love to give it a try!

**Comment by thedist** [comment]
If you log in to the Bitfocus Companion site https://bitfocus.io/user/downloads there's a link to download the 2.2.0 Release Candidate. This version of Companion has significantly more features, not just for vMix but for many modules and Companion itself.

**Comment by shapiroconsult** [comment]
Thank you so much - I will absolutely check it out
