### ISSUE TITLE
"Browser Navigate"- GET

### ISSUE THREAD

**Issue by Tilltv** [bitfocus/companion-module-studiocoast-vmix#146]
There is a problem with the function "browser navigate":
All attached GET parameters are ignored.

it still worked in older versions.

Example URL:
localhost/index.php **?action=test (ignored)**

Companion: 2.2.0+3964-beta-f4241f46
vMix: 24.0.0.72

**Comment by thedist** [comment]
Fixed in the latest commit. When this is next updated in the Companion builds it should all work.

**Comment by Tilltv** [comment]
I tested it and it works! I am impressed how quickly this was repaired. Many Thanks, that helps me alot!
