### ISSUE TITLE
BUG: Check for undefined

### ISSUE THREAD

**Issue by JeffreyDavidsz** [bitfocus/companion-module-studiocoast-vmix#15]
@McHauge could you check lines 655&680 please, with a empty config, you might run into errors

**Comment by McHauge** [comment]
I will take a look

**Comment by McHauge** [comment]
Made a pull request with some small changes reverted the change I made on those two lines in V1.1.3 back to how they were in 1.1.2 since from what I can tell the tally feedback does not support the use of title names instead of index id's
