### ISSUE TITLE
Layers- check is X input is on Layer on Y input, feedback does not match selected Layer

### ISSUE THREAD

**Issue by dlamon1** [bitfocus/companion-module-studiocoast-vmix#152]
**Describe the bug**
When using feedback option [<vmix: Layers - check if X input is on Layer on Y Input>](http://127.0.0.1:8088/api), feedback response is inconsistent with selected layer. Ex, my vmix input toggles between input on layer 3, but vmix companion feedback is toggling response only when set to Layer 0 or 1. 

**Expected behaviour**
Expected feedback response to match selected layer of option <vmix: Layers - check is X input is on Layer on Y Input>

**System**
Windows v10, running from local host. 

- Companion Version (2.2.20-rc2+3956-25a303b7), the current 'release candidate'

**Comment by thedist** [comment]
Fixed in the latest commit. Due to how close Companion is to the 2.2.0 release this may not make it in there, but at the very least will be in a beta build for the next version soon.
