### ISSUE TITLE
Recording variable is not updating

### ISSUE THREAD

**Issue by fhareide** [bitfocus/companion-module-studiocoast-vmix#153]
I can't seem to get $(vmix:recording_hms) to update in the latest version.

**To Reproduce**
Steps to reproduce the behaviour:

1. Start recording
2. Look at variable staying at 00:00:00 in Companion

**Expected behaviour**
This variable should update when recording is running

- Companion 2.2.0 rc2
- vMix 24.0.0.72

**Comment by thedist** [comment]
Fixed in the latest commit, it'll start working when this change makes it into Companions build.
