### ISSUE TITLE
vmix:recording_duration

### ISSUE THREAD

**Issue by Rik83** [bitfocus/companion-module-studiocoast-vmix#156]
vmix:recording_duration -> always show 00:00
vmix:recording_hms-> always show 00:00:00

**Comment by thedist** [comment]
This was fixed in a recent commit that I don't think has made it into the beta builds yet. When the next beta build is released (I believe it'll be `Companion 2.2.0+4005`) try that and see if you still have the issue.

**Comment by Rik83** [comment]
cool. and congratulations for the shift button !
