### ISSUE TITLE
Selected mini mix

### ISSUE THREAD

**Issue by Federico-Catelotti** [bitfocus/companion-module-studiocoast-vmix#158]
The function for managing the M/E (mini mix) being able to tell a button to follow which M/E is selected (selected) is fantastic.
I would like to ask if it was possible to have more "selects".
Often when i work on broadcast mixers i have a desk dedicated to each M/E. I do the same with vmix but i have to copy all the buttons several times.

It would be nice to have more (selected mini mix) (e.g. selected 1, selected 2, selected 3 ...) so that you can have more banks.
I often use 4 streadecks together. I would like to put on the first two streadecks the first/second M/E and if on the other two streamdecks another selected, so that I can manage the second, the third and the fourth.

**Comment by thedist** [comment]
The Companion Beta builds now include a utility action for selecting a mix, and mix selection dropdowns should have a 'selected' option which will use whatever is the selected mix (defaults to the main Mix).
