### ISSUE TITLE
Bug feedback

### ISSUE THREAD

**Issue by Federico-Catelotti** [bitfocus/companion-module-studiocoast-vmix#161]
After about 45 min of everything working correctly, the visual feedback of the keys breaks. If I move the API pooling (decrease / increase) it comes back ok. I also tried to keep it high (1000/1500) but it breaks after a while. The project has only two pages, and has few buttons.
v.2.1.4.

**Comment by thedist** [comment]
2.1.4 is a very old version of Companion. Please update to 2.2.0 and see if the issue persists and if any connection issues are logged which it sounds like could be the problem.

**Comment by Federico-Catelotti** [comment]
I use 2.1.4 because with the most recent I have this problem: 
https://github.com/bitfocus/companion-module-studiocoast-vmix/issues/159

**Comment by thedist** [comment]
2.1.4 hasn't been updated in a significant amount of time and there's no work being done, and if you're seeing connection issues in both 2.1.4 and the in the recent version which you linked then that appears to be a connection issue more than anything else so I'll close this thread and I'll continue to try work on the other issue posted but it's not something I can replicate as none of the local or cloud instances myself or the studios I work with run have encountered connection issues so it is not an easy thing to resolve if we can't replicate.
