### ISSUE TITLE
Chamsys <> vMix Artnet problem

### ISSUE THREAD

**Issue by AHub88** [bitfocus/companion-module-studiocoast-vmix#162]
We use Chamsys (via Artnet) for our lighting control.
When we start a light show, our two Vmix PCs on the network go crazy.

Inputs are loaded up, replays abort etc.

Something triggers these commands:
04/22/04 10:19:02 instance(vMix - Kiosks): Sending command: FUNCTION quickPlay input=Card
04/22/04 10:18:54 instance(vMix - LED Control Room): Command Response: FUNCTION OK Completed,
22.04.04 10:18:54 instance(vMix - SpradeTV): Command Response: FUNCTION OK Completed,
22.04.04 10:18:54 instance(vMix - LED Regie): Sending command: FUNCTION quickPlay input=Sprade%20Output
22.04.04 10:18:54 instance(vMix - SpradeTV): Sending command: FUNCTION quickPlay input=PTZ%20-%20Gate%20right
22.04.04 10:18:29 instance(vMix - LED Regie): Command Response: FUNCTION ER Invalid parameters..,
22.04.04 10:18:29 instance(vMix - LED Regie): Command Response: FUNCTION OK Completed,
22.04.04 10:18:29 instance(vMix - LED Regie): Sending command: FUNCTION SetVolumeFade Value=100,0&input=TOOOOORRR!
22.04.04 10:18:29 instance(vMix - LED Regie): Sending command: FUNCTION quickPlay input=TOOOOORRR!

- There are no scheduled triggers in Companion
- The error occurs when I start the light show via Companion, but also when I start it directly via Chamsys
- If I deactivate Artnet in Companion, the error does not occur anymore
- I've deactivated OSC Listener in Companion, the error occurs
- I've set Chamsys to OSC mode RX, the error occurs

Can you please help me?

THX.
Andi Huber

**Comment by krocheck** [comment]
I'd suspect having the Artnet Listener enabled is your problem if your Companion instance has a network connection with Artnet packets on it.  The Artnet Listener will trigger buttons from the Artnet packets.  Doesn't sound like your configuration needs that, so you should just leave that off.  Chamsys won't require that Artnet Listener to function ... it will manage its own connections.

**Comment by thedist** [comment]
The vMix module itself doesn't do anything with Artnet, and there's nothing that programmatically triggers functions automatically within the module itself, so I don't believe this is an issue with the vMix module.

**Comment by AHub88** [comment]
Thank you for your answers.
Then I leave the Artnet Listener switched off.
