### ISSUE TITLE
Triggers based on tally

### ISSUE THREAD

**Issue by guimacjr** [bitfocus/companion-module-studiocoast-vmix#164]
I know there is triggers based on what is on PGM, but, you only get the to trigger on that exact input and not if the input is on air. It doesn't work if the input is inside a multiview.

**Comment by thedist** [comment]
There are instance variables for `input_<Name/Number/ID>_tally_preview` and ``input_<Name/Number/ID>_tally_program`

So if you want to trigger something when input 3 is in program, `input_3_tally_program` will be `true` when that input is in program either directly or as a multiview layer.
