### ISSUE TITLE
Username / Password

### ISSUE THREAD

**Issue by krisdahl** [bitfocus/companion-module-studiocoast-vmix#166]
**Describe the feature**
vMix has an option now to use a username and password to access the web interface.  It would be great the module could support this authentication. 

**Is this version dependent (vMix v24.)?**
I believe it is a feature that was introduced in v23

**If documentation is required to implement, do you know where to find it?**
[Screenshot of vMix Web Controller admin page](https://www.vmix.com/help23/lib/NewItem363.png)

**Usecases**
There are some cases when you can't lock down a firewall rule, or want the additional security of a username and password for production use.  Supporting the native authentication seems like a good idea.

**Comment by McHauge** [comment]
@krisdahl companion does not use the web interface, everything is over the TCP API, not HTTP, so the username and password are not used anyway, to my knowledge, in vmix 25 you will need to manually enable the TCP API for Companion to be able to connect anyway.

Hope that's a sufficient answer :)
