### ISSUE TITLE
Companion and vMix do not communicate together

### ISSUE THREAD

**Issue by 9734-Jba** [bitfocus/companion-module-studiocoast-vmix#169]
**Describe the bug**
Companion connects correctly on the "connections" page, but when a button is pressed, an error occurs (no log transmitted)

**To Reproduce**
Steps to reproduce the behaviour:

1. Add Vmix as instance.
2. Create a regular button
3. Execute action

**Expected behaviour**
Perform the expected action

**Screenshots**

**System (please complete the following information):**

- Companion Version 2.2.1 (2.2.1+4443-v2-2.1-98594c92)
- vMix version 25.0.0.31 x64
- Windows 10

**Additional context**
Default setup for vMix and Companion (the error does not come from an IP or port configuration problem)

**Comment by thedist** [comment]
I'm not able to reproduce your issue, can you please share your companion configuration.
