### ISSUE TITLE
vMix Feedbacks work for Buttons but not for Triggers?

### ISSUE THREAD

**Issue by rse** [bitfocus/companion-module-studiocoast-vmix#171]
**Describe the bug**
In Companion I can use arbitrary vMix Feedbacks (like Audio Mute/Unmute) to give buttons an optical state just fine, but every vMix Feedbacks I try in a Companion Trigger(!) as a condition does never fire at all as it seems. Even if exactly the same vMix Feedback triggers just fine for the button states and although other non-vMix-Feedbacks also trigger just fine as a condition in Companion Triggers. 

**To Reproduce**
Configure a Companion Button with press action "vmix: Audio - Input Mute" and a feedback of "vmix: Audio - Input mute" plus a separate Companion Trigger with a condition "vmix: Audio - Input mute" and an arbitrary action (in my case an "osc: Send float" for controlling TouchOSC). Pressing the Companion Button toggles audio mute just fine. Also toggling the vMix button for unmute/mute shows the different states of the Companion Button, so the vMix Feedback works as expected. But the Companion Trigger, although based on exactly the same vMix Feedback, never fires.

**Expected behaviour**
I would expect that a vMix Feedback really fires when used as a Companion Trigger condition.

**Screenshots**
(none)

**System (please complete the following information):**

- Companion Version 2.2.3 (Companion vMix-Module 2.0.15),
  I also tried with older beta versions up to 2.2.0 and the problem exists there, too.
- vMix version 25.0.0.32

**Additional context**
(none)

**Comment by rse** [comment]
I've figure out a little bit more details:

1. ALTERNATIVE: when replacing the `vmix: Audio - Input Mute` feedback with `internal: Check variable value` and let this check variable `Input 1 Muted $(vmix:input_1_mute)` the Companion Triggers condition fires. This way one has at least a workaround which allows one to fire a trigger action in case an audio input is muted/unmuted. Good.

2. ADDITIONAL BUG: unfortunately, when I use the name of the input `MIC1` by using `Input MIC1 Muted $(vmix:input_mic1_mute)` it breaks again and when I rename the input 1 in vMix from `MIC1` to `mic1` it also works with the named input based variable `Input mic1 Muted $(vmix:input_mic1_mute)`. It also looks strange that in the code block at https://github.com/bitfocus/companion-module-studiocoast-vmix/blob/e8513004149b8638b8fcc9d997db4df8359f5dea/src/variables.ts#L248 only the lower-cased variables are created, while in the code block at https://github.com/bitfocus/companion-module-studiocoast-vmix/blob/e8513004149b8638b8fcc9d997db4df8359f5dea/src/variables.ts#L697 also the original name is set, too. Perhaps this is already the source of this additional bug. And perhaps also the source of the original problem? Sorry, I still do not know too less about the Companion internals to better judge this...

**Comment by thedist** [comment]
Triggers can only work using basic feedbacks, and as vMix uses advanced feedbacks consistently these can not be used as triggers. This is by design, but we may reconsider using basic feedbacks at a later update (which would be a limited set of feedbacks, as some simply can't be done with basics).

As for your issue with MIC1 not working, but mic1 working, I'm unable to reproduce, and both work fine for me in a variable.
