### ISSUE TITLE
Allow this action to be set by a dynamic value: "vmix:Position - Adjust an Inputs pan/zoom"

### ISSUE THREAD

**Issue by signalmod** [bitfocus/companion-module-studiocoast-vmix#172]
I would like to be able to move an input based on vmix's dynamic values.  This would allow for a latched button to change the amount of movement for each button press. 

https://www.vmix.com/help24/index.htm?DynamicShortcuts.html

While vmix supports dynamic inputs and values, the current implementation of this action only allows for Dynamic Inputs to be used

![Screenshot (15)](https://user-images.githubusercontent.com/110264989/181859529-34c2d670-492b-465f-9790-aa089b028858.png)

Use case: 

For example, by default DynimicValue1 could be set to .5 which would give coarse adjustment.  When a latched button is toggled in companion, this could set DynamicValue1 to .05 for fine adjustment to get the framing perfect.

Currently, the value field only allows for numeric input.  It would be great if it allowed Dynamic1 - Dynamic4

**Comment by JaaHann** [comment]
I have a similar situation. I want to use a companion variable to select a multiview layer, but only numbers between 0 and 10 are allowed. Pasting in the variable name results in "e1" as value.

In general I think it would be very nice to be able to use dynamic values and companion variables as values in all actions.

**Comment by thedist** [comment]
The latest update now allows `Adjust an inputs pan/zoom` to parse variables.

The only reason not all options can yet do this is because some would require an upgrade script so it's not a quick fix, but this one is updated now in Companion v3.
