### ISSUE TITLE
vMix feature request to reset input

### ISSUE THREAD

**Issue by chowhi123** [bitfocus/companion-module-studiocoast-vmix#173]
**Describe the feature**
A clear and concise description of what the feature does
I am requesting a feature to be able to reset inputs.

**Is this version dependent (vMix v24.)?**
No

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc., to help the developers along.

https://vmixapi.com/?function=ResetInput

**Usecases**
Add a couple of use cases for why this should be implemented and when/why to use it.
 When a hardware disconnects and reconnect, I need a quick way to reset the input to bring back by resetting.

**Comment by thedist** [comment]
I've now added a Reset Input action in the latest update.
