### ISSUE TITLE
instance(vmix): Function socket err: read ECONNRESET

### ISSUE THREAD

**Issue by Ystum** [bitfocus/companion-module-studiocoast-vmix#176]
Hi, everyone. I have a problem with my companion. I have streamdeck connected to companion, and also companion have connection with vmix at another PC. In this way, I control vmix via streamdeck. Sometimes, I can't control vmix via streamdeck. Every time, when this happens, I can see messages like this in companion log. After this I must make recconect for continue working. Can you help me, to solve this issue?
![photo_2022-09-10_20-25-27](https://user-images.githubusercontent.com/34417588/191209346-225760ea-b2ba-448d-9fea-0f988eb1c63d.jpg)

**Comment by Julusian** [comment]
It is hard to say from just these details, but I expect that you have connected companion to the http api in vmix instead of the tcp api

**Comment by Ystum** [comment]
You are absolutly correct, we use web contrloler in vmix (probably it's https api). Ask enything what you need. It's very important for me, that that this stuff works correct.

**Comment by thedist** [comment]
Companion doesn't use the HTTP API, so make sure that the configuration of the vMix instance in Companion is set to the TCP port (8099) and NOT the Web Controller port (which would usually be 8088).

**Comment by thedist** [comment]
No response as to if this issue is resolved, so closing for now.
