### ISSUE TITLE
Variables of number and name of layer inputs from preview & programm input

### ISSUE THREAD

**Issue by JaaHann** [bitfocus/companion-module-studiocoast-vmix#178]
I would like to use variables of all numbers or names of layer inputs from the current preview or programm input.

Something like this:
$(vmix:mix_1_preview_layer_1_number)
$(vmix:mix_1_preview_layer_2_name)
$(vmix:mix_1_programm_layer_5_number)
$(vmix:mix_1_programm_layer_7_name)

I do a lot of layer changing during a show, to work more efficient I use the preview input as target of my adjustments, so whatever input is in preview can be adjustet. This allows me to just use a single "setup page" to modify all settings I want to change to whatever input is in preview, instead of having a page per input that can be modified.

For me it would be very handi to get an input by number or name from layers of the current preview or programm input as a variable in companion. For now I would only need to get the inputs of layers from the preview input of mix 1. Adding the same variables for the programm input would be nice as well and to be complete maybe doing the same for all the other mixes too.

**Comment by thedist** [comment]
Added in 85e78cb301c29ce8dd8341be3179940e45614c37
