### ISSUE TITLE
[request] vMix Module - instance feedbacks

### ISSUE THREAD

**Issue by gabrielve1** [bitfocus/companion-module-studiocoast-vmix#18]
Hello there.

As for now **vMix module** is a very powerfull tool for Companion, but it lacks one feature, that renders it very problematic for controlling this software remotely - **FEEDBACKS**.

For starters it would be a powerfull addition if developers make feedbacks at least for vMix functions state (recording, external output, streaming, playlist etc.). 

There is a special section of API XML that provides that informations
Example (taken from my vMix just a moment ago, httlp://127.0.0.1:8088/API/):

```
<recording duration="515" filename1="C:\Users\user\Videos\capture - 23 January 2020 - 02-04-35 PM - 00000.mpg">True</recording>
<external>False</external>
<streaming channel1="True" channel2="True">True</streaming>
<playList>False</playList>
<multiCorder>False</multiCorder>
<fullscreen>False</fullscreen>

```

- Without feedbacks we can controll vMix of course, but if i would like to turn something on remotely i don't have a confirmation it worked.

- Also in my case for example, im controlling multiple vMix productions at once, located in many studios and other locations. This feature would really ease my work (and i think not only mine)

**Comment by gabrielve1** [comment]
anyone?

**Comment by willosof** [comment]
Maybe offer a bounty for it?:)

**Comment by gabrielve1** [comment]
I'll faster write it myself in a free time... when I'll have some ;)

**Comment by thedist** [comment]
This is something I'm actively working on implementing right now. I'm working on quite a comprehensive update (that's non-breaking) to not just add feedback to as much stuff is reasonably viable (so things like preview/program for all 4 mixes, overlays, title text/coundowns, video input time remaining etc...).
