### ISSUE TITLE
Set Vmix Countdown (SetCountdown) via companion variable (string)

### ISSUE THREAD

**Issue by themoog** [bitfocus/companion-module-studiocoast-vmix#187]
**Describe the feature**

As a user I would like to be able to use a companion variable (string 00:00:00) to set the vmix SetCountDown function. This is so I can set the value programmatically instead of the dedicated companion function that does not support variables.

**Is this version dependent (vMix v24.)?** - Probably

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc., to help the developers along.

https://vmixapi.com/?function=SetCountdown

**Usecases**

I can find another way of setting the countdowns duration via a variable, this would be useful to pull different times from another variable (a google cell in my example)

**Comment by thedist** [comment]
Added in a912368c2f7b08bcdfca25387afdf4ef38c9d25d

**Comment by coinkoios** [comment]
Is this possible? I've been trying to SetCountdown from a Google Sheet source too...I'd love to connect all my segment titles, timer lengths and the set countdown function all at once somehow!
