### ISSUE TITLE
vmix: Transition - Send Input to Program Mix always affect Mix 1 no matter which Mix is specified

### ISSUE THREAD

**Issue by richardgatarski** [bitfocus/companion-module-studiocoast-vmix#189]
**Describe the bug**
This action always affect Mix 1 (Active), no matter which Mix number is selected in the drop down.
Works just fine in 2.4.1

**To Reproduce**
Add from Presets the "Mix 2-4" (which btw should be labelled "Mix Inputs", or "Mix 2-16") and select any Mix beyond 1.

**System**
- Companion Version 'win64-3.0.0+5603-beta-5955d21b
- vMix version 26.0.0.27

**Comment by thedist** [comment]
Fixed in 372ba37e2de80f6eeea73495a8e269053106a2e4

You'll need to update to a beta running v3.0.1 of the module
