### ISSUE TITLE
[BUG] vMix ReplayMark function

### ISSUE THREAD

**Issue by danielschon-live** [bitfocus/companion-module-studiocoast-vmix#19]
Hi, I am trying to set up a button on Stream Deck to work as "-5" (or -10, -20) button in Mark section of Instant Replay in vMix. 
Since the vMix doesn't have exact API function for that I am forced to use function "ReplayMarkInOut" with parameter "Value=5000" so the command should look like this (I hope): vMix: run custom command = "ReplayMarkInOut&Value=5000". But this command doesn't work at all. So in the first place I would like to ask you for advice (in case I am doing something wrong). Thank you.!

**Comment by McHauge** [comment]
From my experience with vMix shortcodes, I would expect that command to look like this when used as a custom command, with space before the first value:

"ReplayMarkInOut Value=5000"

if there is more than one parameter use "&" as a separator between then like the example below:

"SetOutput2 Value=Input&Input=3"

**Comment by danielschon-live** [comment]
Thank's a lot! It was really my mistake with the space.
