### ISSUE TITLE
Red error square on button press

### ISSUE THREAD

**Issue by UnrealPinguin** [bitfocus/companion-module-studiocoast-vmix#190]
**Describe the bug**
I believe I have setup the connection instance correct, status is OK and IP is how it should be. vMix is running on the same PC as Bitfocus Companionn, but somehow all my buttons won't work. 
When pressing a button that puts input 1 to program a red error square appears and when you go to the connections tab the vMix connection shows ERROR and then turns back to OK. I cannot find any errors in the logs of companion.

I have reinstalled both vMix and Bitfocus Companion, for a couple of hours it worked and then again stopped working.

**To Reproduce**
I cannot reproduce it because it had appeared out of nowhere.

**Expected behaviour**
It normally should put the input 1 to program.

**Screenshots**
<img width="89" alt="Screenshot 2023-02-13 at 11 49 39" src="https://user-images.githubusercontent.com/51502024/218438377-49886af1-8324-4977-a874-553ca6d2ae14.png">
<img width="435" alt="Screenshot 2023-02-13 at 11 56 21" src="https://user-images.githubusercontent.com/51502024/218439741-09469be5-ed94-4594-8fc5-c56b22b24937.png">

**System**

- Windows 10
- Companion Version [e.g. 2.4.2 (2.4.2+4911-v2-4.2-fcb5a863)]
- vMix version [25.0.0.34]

**Comment by thedist** [comment]
Are you connecting on the correct port? This sort of error is the sort that would happen if you try to connect to the vMix Web Interface port instead of the TCP port.

**Comment by UnrealPinguin** [comment]
> Are you connecting on the correct port? This sort of error is the similar to what would happen if you try to connect to the vMix Web Interface port instead of the TCP port.

Thanks!!
This was indeed the issue.
