### ISSUE TITLE
Is vMix Module Ready for Companion 3.0?

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-studiocoast-vmix#191]
•  Running Companion Version 3.0.0 (3.0.0+5661-beta-b166e95e)
  •  vMix Pro 26.0.0.36 x64

I see a note that the vMix module has been updated for Companion 3.0, but my experience so far is that it is unusable due to the fact that so many actions do not work. Am I misunderstanding the status of this upgrade?

Here are a few items that I have tested. It is certainly not an exhaustive list.

- Fade transition works
- Toggle FTB works
- vmix: Scripting - Script start - does not work
- vmix: Overlay - Functions | Toggle Overlay 3 on program - does not work (it does turn-on the overlay, but does not do it for any input)
- vmix: Input - Send Input to Preview - does not work

**Comment by thedist** [comment]
Companion v3 is in beta with lots of development still ongoing. If you're using the pre built installs then yes you'll have a partially broken module as it doesn't have everything transitioned yet that the latest commits do.

**Comment by ZoomTestKitchen** [comment]
Thanks, Jeff.
