### ISSUE TITLE
DataSource actions are zero-based but this is not documented

### ISSUE THREAD

**Issue by BryanCrotaz** [bitfocus/companion-module-studiocoast-vmix#195]
Data rows in VMix are 1-based. In Companion they are 0-based.

The action should note this in the UI, just as it gives a hint for Name,Sheet,Index

**Comment by thedist** [comment]
vMix themselves document functions that target a specific row as being 0-based index, for example the `DataSourceSelectRow` has the description `Name of the Data Source, Table Name (optional) and Row Index starting from 0 eg 'Excel/CSV,Sheet1,5`.

This is not a bug, but I will mark it as an enhancement to add further descriptions within Companion for those unfamiliar with vMix functions.
