### ISSUE TITLE
vMix not reading custom variables for sending to vmix

### ISSUE THREAD

**Issue by upstreamproductions** [bitfocus/companion-module-studiocoast-vmix#199]
**Describe the bug**
When making a button ex. Input - Send Input to Preview if a custom variable is in the text box instead of grabbing the value of the custom variable it will send the actual text and not the value. example you want to send the value of $(internal:custom_seat) which is set to 24 instead of sending 24 to vmix it will send %24(internal%Acustom_seat).

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a custom variable
2. Assign custom variable a value
3. Create a button with the vMix function: Input - Send Input to Preview
4. Set the set the input to your custom variable
5. Activate button
6. Check log will show %24(internal%Acustom_variable) instead of the value stored.

**Expected behaviour**
The button should send the stored value as in previous releases. Currently using version 2.1.2 where is works flawlessly.

**System (please complete the following information):**
Companion Version 3.0.0+5776
vMix Module Version 3.0.1
vMix Version 26
Windows 10/11
Linux Debian Bullseye

**Comment by thedist** [comment]
Thanks for reporting the issue, I've made a fix and it'll be included in the next patch.

**Comment by upstreamproductions** [comment]
Awesome, Thank you.
