### ISSUE TITLE
Feature Request: Dynamic Input Feedback 

### ISSUE THREAD

**Issue by DanielWilliamsMSC** [bitfocus/companion-module-studiocoast-vmix#205]
**Describe the feature**
Provide Feedback function for Dyanmic Input as per stock activators

![image](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/125619541/30d39b73-1c8b-425a-a669-0e8cb6ba492d)

**Is this version dependent (vMix v24.)?**
Not as far as I'm aware

**If documentation is required to implement, do you know where to find it?**

**Usecases**
Allows Feedback to operator on which Input is currently set on a dynamic input

**Comment by thedist** [comment]
I can create a dedicated feedback for this, but in the mean time you can use the `internal: Variable: Check value` feedback, as each dynamic input/value has a variable, eg `$(vmix:dynamic_X_Y)` where X is either `input` or `value`, and Y is 1 to 4, so you can use that feedback to check if that variable matches a value you specify and change the style of the button if it matches.

**Comment by DanielWilliamsMSC** [comment]
That worked thanks! More rabbit holes to go down with making things more complicated 🤣

**Comment by thedist** [comment]
A recent update includes a `General - Dynamic Input or Value` Feedback to check if a Dynamic Input or Dynamic Value matches a specified value.
