### ISSUE TITLE
Get remaining time from feedback function isnt working anymore in 3.0 RC1

### ISSUE THREAD

**Issue by rfraedrich** [bitfocus/companion-module-studiocoast-vmix#210]
**Describe the bug**
When adding the feedback function "Playback Time" to a button, nothing is displayed"

**To Reproduce**
Steps to reproduce the behaviour:

Just add this function to any button or create a new button.

**Expected behaviour**
It should show the remaining time of the running clip

**System (please complete the following information):**

- Companion Version 3.0 RC1 (stable)
- vMix version 26.0.0.44

**Comment by thedist** [comment]
This is working as intend. Companion v3 is a shift away from using feedbacks to write text on a button, and instead you should be using one of the input remaining variables, and/or Expression Functions.

Variables, where X is the the inputs name, number, or GUID.
`input_X_remaining` - time remaining in MS
`input_X_remaining_ss` - time remaining in Seconds
`input_X_remaining_ss.ms` - time remaining in Seconds and 
`input_X_remaining_mm:ss` - time remaining in Minutes and Seconds
`input_X_remaining_mm:ss.ms` - time remaining in Minutes, Seconds, and MS
