### ISSUE TITLE
Variable references not parsed in Browser - Navigate

### ISSUE THREAD

**Issue by tuomastiihonen** [bitfocus/companion-module-studiocoast-vmix#211]
**Problem:**
References to (internal) variables are not replaced by values in the URL of Browser - Navigate. 

**Steps to reproduce the behaviour:**
1. Add a button with vmix: Browser - Navigate action and enter a browser source as an input (10 in this)
2. In the vmix: Browser - Navigate action, add a URL with an internal variable like 

        https%3A%2F%2F192.168.0.2%2Findex.html%3Fvar%3D$(internal:custom_var)
4. Companion log shows: 
    
    > debug: Sending command: FUNCTION BrowserNavigate Input=10&Value=https%3A%2F%2F192.168.0.2%2Findex.html%3Fvar%3D$(internal:custom_var)
5. The input properties in vMix also show 
    
    > https://192.168.0.2/index.html?var=$(internal:custom_var)

**Expected behaviour:**
The reference to the variable should be replaced by the value of the variable when the action is run.

**System:**
- Companion Version 3.0.0-rc1 (3.0.0-rc1+5909-v3-0.0-rc1-725c3583)
- vMix version 26.0.0.38

**Comment by thedist** [comment]
I'll add this to this to this next update I'm working on,

Please keep in mind though that parsing variables in actions/feedbacks is done on a module by module basis, and has to added to each action/feedback, so it should not be expected that everything will support that usage, and many modules have no support for it at all.

**Comment by tuomastiihonen** [comment]
Thanks. I hummed and hawed between bug report and feature request, but ended up with the wrong one :-) I thought I saw a similar report earlier with the feature already pipelined, but couldn't find it now.

**Comment by thedist** [comment]
Fixed in the latest release
