### ISSUE TITLE
Cannot see tally light when using custom icon

### ISSUE THREAD

**Issue by PLRNA** [bitfocus/companion-module-studiocoast-vmix#220]
Not sure if it's an feature request or it's a bug.
When using a custom icon on a button, this button doesn't display the tally light (for example the tally from overlay state)

**Comment by thedist** [comment]
Have you checked to ensure the icon has transparency?

**Comment by PLRNA** [comment]
Well… You’re right ! I made this icon with elgato key creator and didn’t notice that this tool was not handling transparency.


De : Jeff Martin ***@***.***>
Envoyé : lundi 17 juillet 2023 17:29
À : bitfocus/companion-module-studiocoast-vmix ***@***.***>
Cc : Philippe LIZON ***@***.***>; Author ***@***.***>
Objet : Re: [bitfocus/companion-module-studiocoast-vmix] Cannot see tally light when using custom icon (Issue #220)


Have you checked to ensure the icon has transparency?
