### ISSUE TITLE
T-bar changes don't send to vmix

### ISSUE THREAD

**Issue by Oldman-Winter** [bitfocus/companion-module-studiocoast-vmix#225]
**Describe the bug**
I have the T-Bar option enabled in the Vmix config but it does not send the changes to vmix.

**To Reproduce**
Steps to reproduce the behaviour:

1. In Companion, go to 'connections'>'vmix StudioCoast'
2. Click on 'Enable' beside the 'T-Bar' option
3. Disable the 'set fader' shortcut in Vmix settings under 'Shortcuts' (Shouldn't matter for installs on a separate PC)

**Expected behaviour**
I'm expecting the T-bar on the xkeys to update the tbar position in the vmix install on the remote PC.
Nothing happens.

Also can't set the t-bar position with a variable only a specific value.
As a work around I've made a couple triggers to monitor the $(internal:t-bar) variable and trigger a vmix transition if is 255 and one for 0.

**System (please complete the following information):**

- Companion Version 3.0.0
- vMix version v26.0.0.45

**Additional context**
I have 2 vmix installs and 1 xkeys + 1 stream deck
Companion is installed to sync the 2 productions in case one PC goes down.

**Comment by thedist** [comment]
The module itself can't directly read state changes for a t-bar, so in the latest version of the module more support for instance variables have been added on certain functions where it has been requested to support the `$(internal:t-bar)` variable such as replay speed, and t-bar position.
