### ISSUE TITLE
vMix node crashes with unusual status afterward

### ISSUE THREAD

**Issue by RayHAz** [bitfocus/companion-module-studiocoast-vmix#227]
**Describe the bug**
The vMix node crashes daily, leaving a status of "Unknown Stopped"; unable to restart/reset from Companion Toggle Connection action

**To Reproduce**
For me, just starting Companion, or restarting the vMix node by clicking Disable Connection followed by Enable Connection, starts a new node process.  Some time later (usually many hours later, but often multiple times a day), the node crashes, leaving this appearance on the Connections dashboard:
![image](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/10144077/22226770-5bd3-4cc4-b8d3-fac5466a0277)
Note that the Enable/Disable button shows the Connection to still be On.
 
On my Companion Status page (each Connection has its own status feedback, and press actions to toggle the Connection on/off), the vMix status shows 
![image](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/10144077/ae3196e9-0476-46a0-99f2-73217972d135)

At this point, pressing the vMix button on the StreamDeck has no effect... it will not toggle the Connection ON because some part of Companion thinks it IS on.  The only recourse is to pop into the web page GUI and manually toggle the Connection OFF, then ON again.  Ultimately, this restarts the node, and the vMix status shows green, and all is operational again.

**Expected behaviour**
Something should monitor the status of nodes, and if a node crashes, it should set the toggle switch to Enable Connection, not leave the button as Disable Connection.  Alternatively, a new Feedback status of "Failed" should be created AND the interface should recognize the Toggle Connection action to Disable the connection, allowing a second press to successfully re-Enable the connection.

**Screenshots**

**System (please complete the following information):**

- Companion Version 3.0.0.rc2+5989-stable-4d17e724
- vMix version vMix Max - 20-0-0-34 x64
- PC running Windows 10 build 19045; Xeon 1290P CPU; 64G RAM; Intel P630 + NVIDIA Quadro RTX 5000 GPUs

**Additional context**
Note that the node crash is often preceded by a significant increase in Working Set, probably indicating a memory leak or other internal issue.  Fixing this issue might prevent the node crash, but there should still be a code/configuration change that doesn't deadlock the Toggle Connection action under "unusual circumstances" such as "Unknown Stopped" shown above.

**Comment by thedist** [comment]
Modules have no control over that Enabled/Disabled toggle. That's entirely within Companion itself and not something modules have any control over so it's not something I can assist with other than suggestion you make an issue on the Companion repo.

As for the crashing. You'll have to show your yours for the vMix module because there's nothing I can do if you haven't shown anything that may indicate a fault. Only thing I can suggest right away is that 1. you're using an old version of Companion, v3 is fully released now you don't need to use a Release Candidate, 2. vMix 20 is WAY before our supported versions, support started with vMix v24, and even that is beyond what we can test with now as v26 is current.

**Comment by RayHAz** [comment]
Sorry, the one typo I didn’t catch: vMix 25. I’ll update both vMix and Companion to the latest today and see if the problem goes away. If it continues, I’ll re/cross-post to the Companion hub. 

You wrote “show your yours”: If there’s more info I can provide here just in case it might help with why the node.exe is crashing, let me know. My programming days pre-date GitHub so I’ll need just a little guidance. 😎

Thanks for the help!

**Comment by thedist** [comment]
I meant show me your logs. On the connections screen click the `>_` button to view the logs for that module.

**Comment by RayHAz** [comment]
Updated vMix to 26 (from 25) and Companion from rc2 to 3.0.0. VMix node.exe has **not** crashed in 24 hours!  Yay!

My issue is now a non-issue. Thanks @thedist for your input and assistance here! 

I use vMix only for Zoom and local recording … and I use Companion for almost everything on my Windows desktop!  I appreciate the teamwork that goes into this.

**Comment by RayHAz** [comment]
I’my, Close button!
