### ISSUE TITLE
Replay Speed

### ISSUE THREAD

**Issue by ErwinBeenhakker** [bitfocus/companion-module-studiocoast-vmix#228]
**Describe the bug**
Setting replay speed only allows 1 and -1, any value in between doe not work.

**To Reproduce**
create button for stream deck
select: replay change speed function
set speed, for example 0.5

**Expected behaviour**
using button does not change speed setting

- Companion Version 
- v3.0.1+6068 stable a05a9c89

- vMix version [e.g. v23]
26.0.0.45 x64

Best regards,
Erwin

**Comment by thedist** [comment]
I'm not able to reproduce this issue, the function works just like `replayChangeSpeed` should in vMix where it adjusts the current replay speed by the value (so it does not set to an absolute value) and appears to work fine on my end.

**Comment by thedist** [comment]
In the latest update, I've now added an action `Replay Set Speed`, this allows you to set a specific speed value, rather than the Change Speed action which adjusted the current speed by the provided amount. Hopefully this meets your needs.
