### ISSUE TITLE
Cannot update connection IP/port when current connection configuration is timing out

### ISSUE THREAD

**Issue by morleym** [bitfocus/companion-module-studiocoast-vmix#229]
**Describe the bug**
When an attempted connection to a vMix TCP ip:port times out, user is unable to effectively edit the connection information in the module.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to connection configuration
2. Enter an ip:port which will time out, and click save on the connection (for example, pointing at the wrong port or attempting to access vMix from outside of a LAN where 'restrict to LAN only' is enabled in vMix settings for the TCP API)
3. Wait for connection to time out (displayed in log)
4. Attempt to edit the connection and save the new connection information

**Expected behaviour**
Connection edits are saved, and new attempts to connect are using the updated ip:port

**Screenshots**
![image](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/31675433/b768e1cc-1457-4ba6-bf65-36bee3940df5)

![image](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/31675433/27ea7e31-cc79-43c5-8b55-2673cafe3851)

![image](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/31675433/af02012d-a4f7-40bf-ae31-d01bcefacc76)

**System (please complete the following information):**

- Companion Version 3.0.0 (3.0.0+6049-stable-126f27e8)
- vMix version 26

The device running Companion is a desktop PC running Windows. Ample CPU/RAM specs (as opposed to a Pi or low-spec laptop)

![image](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/31675433/270d89b6-8488-4735-b91e-fbba86db47e9)

**Additional context**
The 'save' button is also shown as disabled when I click it. But the connection configuration panel won't open unless you 'enable' the connection, which is the state in which this bug occurs  (with information that is timing out)

**Comment by thedist** [comment]
Some of the retry TCP connection logic has been fixed in the latest version of the module, so this should now be resolved.
