### ISSUE TITLE
Functions: SetVolumeChannel1 and SetVolumeChannel2 missing

### ISSUE THREAD

**Issue by chananbos** [bitfocus/companion-module-studiocoast-vmix#230]
For now I am forced to use companion's generic http module for this as the functions SetVolumeChannel1 and SetVolumeChannel2 are missing from the vMIX module.

But the API does support them so it should not be hard to add. The issue with not having it part of the modile, is that I can't set up feedback (or maybe I just don't know how to), it would be great to have feedback for this so I can see if volume on channel 1 or 2 is set to 0 or 100.

**Comment by thedist** [comment]
There's a `Scripting - Run custom command` action to perform all vMix functions. This allows for using functions that are niche and not used/requested enough to have a dedicated action for.

As for Channel volume, vMix's API does NOT provide channel volume data. Activators provide it, but as that only sends messages on changes and does not give the initial state of the channels for each input we don't currently utilize it. If it was included in the API then we could easily read the state and it would be simple to make a feedback/variables for it.

**Comment by thedist** [comment]
There's now a `Audio - Set Input Channel Volume` action, for setting the volume on a specific subchannel of an input.
