### ISSUE TITLE
virtual ptz

### ISSUE THREAD

**Issue by Dveadsl** [bitfocus/companion-module-studiocoast-vmix#234]
Hi everyone, 

there are all the commands to control the PTZ cameras, 
but I can't even find a command to move a virtual PTZ... 
can you help me? 
Thank you

**Comment by thedist** [comment]
All of the vMix functions are accessible through the `Scripting - Run custom command` Action.

So if you wanted to move a PTZ down, you could use `PTZMoveDown Input=ptz1&Value=0.2` to move down on the input ptz1 for example.
