### ISSUE TITLE
When using vMix variables, an adjusted title text is cut off from an ampersand character onwards

### ISSUE THREAD

**Issue by jarihakkarainen** [bitfocus/companion-module-studiocoast-vmix#235]
**Describe the bug**
I have a GT Title that updates its values from a DataSource. I use an action in Companion to set the value of a Title layer to that of another Title layer using vMix variables. It works but if the read value includes an ampersand (&), the written value gets cut off from that character onwards.

**To Reproduce**
Let's suppose the title "TG" has the text "H&M retail stores" in layer 7 and I want to copy that text to the title.Text layer using vMix variables.

Vmix: Title - Adjust title text
- Input: TG
- Layer: title.Text
- Adjustment: Set
- Value: $(vmix:input_tg_layer_7_titletext)

**Expected behaviour**
title.Text should be replaced by whatever value the variable $(vmix:input_tg_layer_7_titletext) has, in this example "H&M retail stores" but instead title.Text reads just "H" after the action. 

**System (please complete the following information):**

- Companion Version 3.1.2 (3.1.2+6243-stable-05c37a10)
- vMix version 26.0.0.45

**Comment by thedist** [comment]
The `Title - Adjust title text` action now has a new option to `Encode Value`, this will encode whatever the string of text you put in the action is, so that special characters should now work with the action.
