### ISSUE TITLE
Set output source for Output 1

### ISSUE THREAD

**Issue by npSpeakerBee** [bitfocus/companion-module-studiocoast-vmix#237]
I'm able to set output source for all other outputs through "vmx: Output - Set Output Source" but not able for Output 1.

Would be nice as a potential failsafe for when vmix configs have been through the trenches and not set correctly back up.

Understand that vmix api doesn't include info for Output source, but does that block setting the output 1 source?

Thanks in advance - npsb

**Comment by thedist** [comment]
Output 1 is your main vMix program output. If you want to change it's source, you simply transition Mix 1 to whatever source you want.
