### ISSUE TITLE
virtual ptz

### ISSUE THREAD

**Issue by Dveadsl** [bitfocus/companion-module-studiocoast-vmix#239]
https://github.com/bitfocus/companion-module-studiocoast-vmix/issues/234

@thedist 

thank you for this.... it's wondefull  but my question is for VIRTUAL PTZ is possible make all command for virtual ptz?

**Comment by thedist** [comment]
The only PTZ commands that are specific to Virtual PTZ is `PTZCreateVirtualInput`, `PTZUpdateVirtualInput`, `PTZMoveToVirtualInputPosition`, and `PTZMoveToVirtualInputPositionByIndex`. All of which were added in the update.

The PTZ commands such as Move Down, all work for vMix's Virtual PTZ too. So I'm not sure what you're wanting, as all of vMix's PTZ control capabilities have been implemented in this module.

**Comment by Dveadsl** [comment]
> The only PTZ commands that are specific to Virtual PTZ is `PTZCreateVirtualInput`, `PTZUpdateVirtualInput`, `PTZMoveToVirtualInputPosition`, and `PTZMoveToVirtualInputPositionByIndex`. All of which were added in the update.
> 
> The PTZ commands such as Move Down, all work for vMix's Virtual PTZ too. So I'm not sure what you're wanting, as all of vMix's PTZ control capabilities have been implemented in this module.

in companion if I search for the move up command, find ptz1, ptz2, ptz3, ptz4 (my camcorders) I can't apply move up to a non-ptz input.

I organize lots of interviews with teams and ndi... I create an input on vmix in ndi, and through virtualptz I can arrange the shots (remote guests are often not competent to take good shots) then with virtual ptz I do a bit of zoom and then arrange right/left/up/down. practically I would need to be able to have the ptz commands (zoomin zoomout up down right and left) on an input that I decide


thank you

**Comment by Dveadsl** [comment]
[
![Screenshot 2023-12-14 163844](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/146434409/7fc61509-2fcf-40bf-817f-b649bfae1a85)
![Screenshot 2023-12-14 163924](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/146434409/11a2144d-6e44-4825-8ab8-dacb8cef1c27)
](url)

ptz ok

virtual no find command

**Comment by Dveadsl** [comment]
> Have you correctly set up the input you're attempting to control as a Virtual PTZ and connected to it?
> 
> When an input is set as a Virtual PTZ and Connected, adding the `PTZ - Move` action in Companion, with the input, movement, and value set, it all works as intended. I can't reproduce an issue of it not working.



![Screenshot 2023-12-14 163844](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/146434409/8246d765-a0ff-4ac2-bb5f-c1847f7c1636)
![Screenshot 2023-12-14 163924](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/146434409/5b826df6-c6df-41c8-8243-513a80ec80c1)



ptz ok

virtual no find command

**Comment by Dveadsl** [comment]
![Screenshot 2023-12-14 164322](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/146434409/2af2e4cb-4f45-4c87-bcce-0adc9e1c6c3d)

**Comment by thedist** [comment]
![ptz action](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/12213790/034b0bda-99a4-48f1-b0d4-f76a1c562c4c)

The Actions to control the PTZ all start with `PTZ - `. If you don't have them, then you're running an old version of Companion, download the latest Beta.
