### ISSUE TITLE
Triggers not reading VMix variables

### ISSUE THREAD

**Issue by nigelmercer** [bitfocus/companion-module-studiocoast-vmix#244]
**Describe the bug**
I have set up some triggers to monitor when a specific input is in Program.  I can see the variable changing in Companion when that input is transitioned to Program.  $(vmix:mix_selected_program).  If I set up a button to read that variable, the correct input number shows on the button as you transition between inputs, so Companion is reading the variable value.
However, if you set up a trigger using that variable (On variable change), it never fires the trigger.  

**To Reproduce**
Steps to reproduce the behaviour:

1. Set up a trigger using "On variable change" as the event.
2. Set the condition to: Internal: Variable: Check Value and enter the variable: $(vmix:mix_selected_program)
3. Set the Operation to =
4. Set the value to the desired input that should trigger when moved to program (Input 3 for example)
5. Set the action you want to use (for example, update a custom variable with the input number.
6. Transition the input from preview to program to see if the trigger fires. (It does not)

**Expected behaviour**
When the input set in the condition described in the trigger is moved to Program, the trigger should run, executing the action described in the trigger.

**System (please complete the following information):**

- Companion Version [3.2.0 (3.2.0+6663-stable-b83f412f]
- vMix Max [v27.0.0.64]

**Additional context**
I am using triggers jointly with VMix and ZoomOSC so that when a user in Zoom raises their electronic hand, it activates a layer in VMix on that guests input (simply a gif of a hand).  These triggers work flawlessly and are based on custom variables that activate a VMix layer or deactivate it based on the ZoomOSC variable for Zoom Hand raises.  The last step in the chain is to automatically lower a speakers hand when they move into speaker view in VMix (when their input is pushed to Program).  This is the part that doesnt work.

**Comment by thedist** [comment]
I can't replicate your issue, it's working perfectly fine on the machines I have to test it on.

![triggerTest1](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/12213790/693ca0bc-c95f-49e6-928c-bfe9aa170c79)
![triggerTest2](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/12213790/36251a5f-7340-4ae5-b990-61e060774f04)
![triggerTest3](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/12213790/bc4661de-b838-4d4d-add5-7db1d25d5d4a)

In this trigger I have it set to the event for `$(vmix:mix_selected_program)` changing, with the condition that the variable equals 1 (ie, the first input), and when that condition is met increment a custom variable. The event, condition, action, and the trigger itself are all enabled. With Mix 1 selected (the default), every time input 1 is in transitioned to mix 1 program the test variable increments indicating that the trigger fired and everything worked as it shoudl.

**Comment by nigelmercer** [comment]
> I can't replicate your issue, it's working perfectly fine on the machines I have to test it on.
> 
> ![triggerTest1](https://private-user-images.githubusercontent.com/12213790/300449656-693ca0bc-c95f-49e6-928c-bfe9aa170c79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1OTA0ODAsIm5iZiI6MTcwNjU5MDE4MCwicGF0aCI6Ii8xMjIxMzc5MC8zMDA0NDk2NTYtNjkzY2EwYmMtYzk1Zi00OWU2LTkyOGMtYmZlOWFhMTcwYzc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA0NDk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyMjJiMGU3ODNmODg2MzM1NzVjNjhiNWY0MTZlNGU2NzJkYTMwMmU0MjYyNDU2YmZiZWUxMzM3ZWM2OTJmMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WovW_j92eKfkQhiYl5XvAgdEKxl02F-ShgHKqR--c3I) ![triggerTest2](https://private-user-images.githubusercontent.com/12213790/300449659-36251a5f-7340-4ae5-b990-61e060774f04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1OTA0ODAsIm5iZiI6MTcwNjU5MDE4MCwicGF0aCI6Ii8xMjIxMzc5MC8zMDA0NDk2NTktMzYyNTFhNWYtNzM0MC00YWU1LWI5OTAtNjFlMDYwNzc0ZjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA0NDk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhYzM3Y2I0NTQzZDkwY2Y3NWQ4ZDEzMzMxYzIwMzIxN2E4ODJlZjIyYzliZjNlNWRjZjQ2NjNhYzBlMDlmNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7AKag051aZO3OJIXpPtKfcyQGzjrdTYu4ixajfXB6vg) ![triggerTest3](https://private-user-images.githubusercontent.com/12213790/300449661-bc4661de-b838-4d4d-add5-7db1d25d5d4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1OTA0ODAsIm5iZiI6MTcwNjU5MDE4MCwicGF0aCI6Ii8xMjIxMzc5MC8zMDA0NDk2NjEtYmM0NjYxZGUtYjgzOC00ZDRkLWFkZDUtN2RiMWQyNWQ1ZDRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA0NDk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4MzY1MmNkMjRjNDMwZGRiYmM0NWVhMmY3ODM5ZGY2YTlhMTljYmFiMGE5ZmE0MTA4MzBjNDgxNTllZGJkMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WGX2XCFQdXAVk8-H3jy5qirrtSiEKIfMenueO5F-_0Y)
> 
> In this trigger I have it set to the event for `$(vmix:mix_selected_program)` changing, with the condition that the variable equals 1 (ie, the first input), and when that condition is met increment a custom variable. The event, condition, action, and the trigger itself are all enabled. With Mix 1 selected (the default), every time input 1 is in transitioned to mix 1 program the test variable increments indicating that the trigger fired and everything worked as it should. Also, the log shows `24.01.29 12:24:36 Controls/ControlTypes/Triggers: Execute triggerTest` when the event and condition are met and the action fires so that further shows everything is working.
> 
> If you've checked that everything is enabled, and set correctly, and it still doesn't work then please click the download button next to to the trigger and attach it here so I can test what you've set.

Interestingly, I had to paste the correct variable in, they did not appear in the dropdown.  For some reason, they now do appear in the dropdown.  When I pasted the variable in, it does not work.  When I choose the variable from the list, it all works.

**Comment by thedist** [comment]
That would be an issue with what was being pasted then. I attempted to manually type in a variable and it looks like it's expecting the variable to be entered without the `$()` around it, and once something is typed if you try to use that (rather than selecting one of the suggestions) it'll automatically add `$()` around whatever you typed, so if you had included that in your copy/paste, that's why it didn't work.

**Comment by nigelmercer** [comment]
Thanks so much Jeff

Really appreciate your help

Kind Regards
Nigel

On 30 Jan 2024, at 13:15, Jeff Martin ***@***.***> wrote:

﻿
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

CAUTION - This email originated from outside APMG.
Do not follow instructions, click links, or open attachments unless you recognise both the senders name, email address and know the content is safe.

That would be an issue with what was being pasted then. I attempted to manually type in a variable and it looks like it's expecting the variable to be entered without the $() around it, and once something is typed if you try to use that (rather than selecting one of the suggestions) it'll automatically add $() around whatever you typed, so if you had included that in your copy/paste, that's why it didn't work.
