### ISSUE TITLE
AUDIO BUS ENABLED IN A SPECIFIC INPUT

### ISSUE THREAD

**Issue by nikosman88** [bitfocus/companion-module-studiocoast-vmix#246]
Hello. Is there any way to have the info if an audio bus is enabled for specific vmix input? This info is provided in vmix api xml. This can be usefull for monitoring cases in a button or do something based if the x bus is enabled for x input
Thank you very much

**Comment by thedist** [comment]
This already exists, the `Audio - Input Bus Routing` feedback.
Select the input, select a bus, and it'll indicate if the input is sending to that bus or not.
