### ISSUE TITLE
Add ability to use custom variables in command options

### ISSUE THREAD

**Issue by TracyPeterson** [bitfocus/companion-module-studiocoast-vmix#250]
When a custom variable is defined in the system (or even a shared variable from other connections) we would be able to use the variable in a text entry field for a command.  For instance an input name could be set in a custom variable then a command button such as "set to preview" could have the input field use $(variablename) to select that stored input name.   This could help operators build complex commands.

**Is this version dependent (vMix v24.)?**

no

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc., to help the developers along.

**Usecases**

I want to set an input to be the graphics template to be set to overlay layer toggle.  The toggle will use the variable name.  I can then make a page of multi step buttons that set data to the template and then set that template input name to the variable.  Similar to using a preset but allows the user to set the input based on other factors in the system including other triggers or data changes.

Through the use of expressions the user can have an command dynamically follow changing internal values such as data source changes, volume of inputs,  It opens the opportunity to create automation through conditional changes.

**Comment by thedist** [comment]
Most actions/feedbacks already support using variables. Which ones are you trying to use where that isn't supported?

**Comment by TracyPeterson** [comment]
I am attempting to use vmix: overlay - functions and to use a custom
variable $(internal:custom_GFXSelectedInput) to set the current take target
for a layer, so that I can target an overlay with a specific input.  As I
described in the use case.  The "Input" text block does not evaluate the
variable.

**Comment by TracyPeterson** [comment]
Also I'm using companion Pi 3.2.2 and the module appears to be v3.5.4

**Comment by thedist** [comment]
I just tested, and using variables works perfectly fine on that action, it just doesn't offer variable suggestions as you're typing them but they'll still be parsed and work in the function.

**Comment by TracyPeterson** [comment]
Jeff,

Thanks for testing this with me, I found the issue and it was one hundred
percent my fault, It worked on my desktop version and i compared configs
and found an offending clear variable command that needed an added delay.

You can mark this request, "nut loose behind keyboard" if you like.

Thanks again.

T
