### ISSUE TITLE
vMix Zoom Plugin Controls

### ISSUE THREAD

**Issue by knbpixels2** [bitfocus/companion-module-studiocoast-vmix#251]
Requesting controls added to the StudioCoast vMix module to include functions used by the vMix Zoom plugin such as "Change Participant Source", "Participant Source type"

**Comment by thedist** [comment]
vMix doesn't have any functions for controlling Zoom inputs, and provides no data about them in their API, so it's not currently possible for Companion to do what you've requested.

Speaking with the Zoom developers themselves they even brought up that there's functionality that is available in their SDK that vMix simply doesn't utilize, so unfortunately in seems like vMix released v27 with half-finished Zoom support.
