### ISSUE TITLE
Webrequest vMix to Companion (3.2 or 3.3)

### ISSUE THREAD

**Issue by danielwernitz** [bitfocus/companion-module-studiocoast-vmix#260]
We want to press a companion button with a vMix webrequest in the new companion version 3.2. (we also tried already with 3.3 Beta). Using the old 3.1 Version the functions are working (page/button).

We tried the webrequest in the old button structure and also the new one (Page/button -> page/row/line)

**Comment by thedist** [comment]
If you're trying to use the Companion API to press a button, first off this has nothing to do with the vMix module as that's general Companion functionality.

Secondly, how are you making the request? The new API requires you to make a POST request, so if you're making a GET request then that wont work.

**Comment by thedist** [comment]
Well you're writing VB.NET vMix scripts, so I'd recommend checking the documentation for VB.NET so you can familiarize yourself with the code you're writing/running.
