### ISSUE TITLE
vMix countdown timer Time Remaining variable for trigger conditions

### ISSUE THREAD

**Issue by knbpixels2** [bitfocus/companion-module-studiocoast-vmix#265]
**Describe the feature**
Pull in the time remaining for a countdown timer and use it as a variable when creating a trigger condition.  We already have time remaining of a countdown as a variable for buttons, would love to have it for triggers as well.

I understand that vMix may be reporting the time remaining as a text string perhaps and that's why we don't have it as a trigger variable, but if that's the case could maybe it be translated into timecode?

**Is this version dependent (vMix v24.)?**
No

**If documentation is required to implement, do you know where to find it?**
N/A

**Usecases**
With this feature users would be able to create a condition that drives a trigger, for example....when a countdown reaches 30 seconds remaining, the condition becomes true, and an action such as Playback of an audio or video input is performed.

**Comment by thedist** [comment]
Why can you not simply use the internal `Internal: Variable: Check value`, or `Internal: Variable: Check boolean expression`, conditions? That's how people so far have been having triggers fire when timers reach a certain value, or are within a certain range.

**Comment by knbpixels2** [comment]
I tried this as well and couldn't get it to work...I have now remade the trigger doing as you describe and still not working, but maybe I'm doing something wrong on the Events section?   I've tried "On Condition becoming true" as well as "On variable change", with my timer variable pasted in:  "$(vmix:input_timertest_layer_0_titletext)", which I can see displaying the countdown time as it runs on the variable tab.   So I know the variable is good.   

Then in the condition I have Internal: Variable: Check Value, using that same variable expression, Operation is =, and value is 00:00:30, which matches the format of the countdown.

But at that mark in the countdown, the action is not triggered.  The action works, based on the Test button.  The test action is to change the background color of a button.

I tried Boolean for a moment but I'm not confident I was doing that correctly, didn't work anyway

**Comment by thedist** [comment]
So your Trigger is set up like the following:

![chrome_ttg412la7z](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/12213790/55ba27ec-3a9a-410d-9fef-7ee83b628ed3)

With the correct Variable set as the `On variable change` Event, the correct Variable and Value set as the `internal: Variable: Check value` condition, and also that the trigger itself on the list of triggers is set to Enabled?

In my quick test there I have a countdown on layer 0 of input 11, it's just using minutes and seconds so my condition just uses minutes and seconds, but if yours uses hours make sure you have it exactly as the countdown will show.

**Comment by knbpixels2** [comment]
Ah ok, I see where I went wrong...I was using a variable from the variables tab, not that specific layer 0 variable you're referencing...I got it working now, thank you!    It would be really nice if vMix could just add a trigger for OnCountdownTime in addition to the existing OnCountdownCompleted, so we don't have to come up with workarounds.    I appreciate your help!

**Comment by knbpixels2** [comment]
> So your Trigger is set up like the following:
> 
> ![chrome_ttg412la7z](https://private-user-images.githubusercontent.com/12213790/330232074-55ba27ec-3a9a-410d-9fef-7ee83b628ed3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NjE2OTYsIm5iZiI6MTcxNTY2MTM5NiwicGF0aCI6Ii8xMjIxMzc5MC8zMzAyMzIwNzQtNTViYTI3ZWMtM2E5YS00MTBkLTlmZWYtN2VlODNiNjI4ZWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA0MzYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMGYwNGUyZWM1YTA3ZTE2M2IwNjY1Y2NiMTk5YjUxZmRjNTU4ZDU0Y2U3YjczNWY5NGY5YmFmMGZjMzZmM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hnq3CONlPJsOzqEy6Hse22G0VAEfJeY3j_5gsjKBFqQ)
> 
> With the correct Variable set as the `On variable change` Event, the correct Variable and Value set as the `internal: Variable: Check value` condition, and also that the trigger itself on the list of triggers is set to Enabled?
> 
> In my quick test there I have a countdown on layer 0 of input 11, it's just using minutes and seconds so my condition just uses minutes and seconds, but if yours uses hours make sure you have it exactly as the countdown will show.

I thought I had it working, and it does work for something like a countdown for a specified time interval.    But it seems like this method does not work when using "Countdown to Time".   

See screenshot below....the layer 0 Title Text variable is pulling from the dynamic text field being generated by vMix, which on a typical countdown is determined by the time interval you specified in the setting.  But when you use Countdown to Time that dynamic text area is populated by the parameters that determine the time to count to and the format.   So when the variable is pulling in the Title Text, it's pulling that, instead of the countdown that is being shown on the input.  So the trigger won't fire because the variable doesn't match the value I'm putting into the trigger

![image](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/160356520/f3a5a575-b703-436a-9e97-3d1925f17846)
![image](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/160356520/b43bd740-ca26-4065-a8b0-8665dc8be10c)

**Comment by thedist** [comment]
Unfortunately there's absolutely nothing we can do about that. When using countdown to specific time, vMix's API doesn't show us what is actually being displayed on the title, so if you have a countdown to `{0:11:36 PM|mm:ss}` the API shows us exactly that string and not what the actual time remaining is.

All I can suggest for that usecase is to submit a feature request on vMix's forums to add the actual time remaining being displayed in the API, which would allow 3rd party apps like Companion to use that data. Or depending on your needs you may be able to use the `Time of Day` Event within Companion triggers and having Companion trigger off of the time of day, rather than compare vMix's countdown, but be aware though if Companion and vMix are on different machines their clocks may not be exactly in sync.

**Comment by knbpixels2** [comment]
That's too bad, thanks for the info!
