### ISSUE TITLE
Add SetTextColor as an action to change text color in titles

### ISSUE THREAD

**Issue by BryanCrotaz** [bitfocus/companion-module-studiocoast-vmix#268]
**Describe the feature**
Accept a hex value to set the colour of a text layer in a VMix Title. Colour, layer and input name should all accept variables
Layer should accept layer name or index

**Usecases**
Multiview title with text colour acting as a tally light
Score changing color based on a threshold
etc

For extra points, also implement the other SetTextXXX shortcuts as actions

**Comment by thedist** [comment]
The latest update now includes `Title - Adjust title text Color` and Title - Adjust title text visibility` actions for adjusting text colour and visibility.

These should also support layer name or index, and I'm planning on rolling that support to all other actions over time too that don't already support it.
