### ISSUE TITLE
Specific Stream Start and Stream Stop Output Function Start All Streams

### ISSUE THREAD

**Issue by oa-refined-heart** [bitfocus/companion-module-studiocoast-vmix#270]
**Describe the bug**
When using `vmix: Output - Output Functions` with the Start Stream or Stop Stream function for a specific stream value like 1, and you have multiple streams configured in vmix, then all the streams are triggered. When using the Start/Stop Stream toggle, then only the specific stream value that I entered starts streaming.

**To Reproduce**
Steps to reproduce the behaviour:

1. Configure multiple streams options on vmix. (I tested with multiple YouTube Live Stream Now instances for the same YouTube account)
3. Create a button in bitfocus using `vmix: Output - Output Functions` and configure it with the Start Stream output function and the stream value as 1
4. Press the button
5. See that all streams are started instead of just 1.

**Expected behaviour**
I would expect that only the specified stream start in this case.

**System (please complete the following information):**

- Companion Version: 3.2.1 (3.2.1+6676-stable-fa981d25)
- vMix version: v26.0.0.5

**Comment by thedist** [comment]
Fixed in f40dc3d43e6b61dadfa839fef2748219af0655e8

This will shortly be available in the next Beta build today, and some time after in the v3.3.1 Companion Stable when that's released.
