### ISSUE TITLE
vMix PTZ - Move Stop command is not triggering a stop for pan/tilt

### ISSUE THREAD

**Issue by kj4awr** [bitfocus/companion-module-studiocoast-vmix#275]
**Describe the bug**
I have setup Companion to pan and tilt and set the release button command to stop the action, however it does not stop

**To Reproduce**

1. Set Camera as input 1 in vMix
2. Enable UVC PTZ for the input
3. in Companion set Press action to vmix: PTZ - Move (Input=1, Move=Left)
4. in Companion set Release action to vmix: PTZ - Move (Input=1, Move=Stop)
5. Press button and release.. the panning continues until camera can no longer pan
6. Go to vMix PTZ control in UI - pan left - when let go it stops

**Expected behaviour**
in step 5 - when releasing button panning stops (same for tilt when applied)

**Screenshots**

**System (please complete the following information):**

- Companion Version 3.3.1 (3.3.1+7001-stable-ee7c3daa)
- vMix version 27.0.0.81
- Stream Deck XL 6.7.0 (20977)

**Additional context**

**Comment by thedist** [comment]
In the list of Companion connections, click the `>_` button next to your vMix connection to open the logs, make sure debug is enabled, and check to see that it is sending the stop command. If it is sending the stop command and it's not stopping then that's not a Companion issue, but a vMix issue, and is not the first time that vMix has had this issue.
