### ISSUE TITLE
Mix 1 Tally flashes when I change a program in other mixes. Tally for other mixes works fine

### ISSUE THREAD

**Issue by semenovnick** [bitfocus/companion-module-studiocoast-vmix#277]
**Describe the bug**
Tally program/preview feedback, any variable with mix_1_program_name, mix_1_tally for **mix1** (Main) flashes (variables changing their values, then coming back) when I change the program/preview in other mixes

**To Reproduce**
Steps to reproduce the behaviour:

Add more mixes to vmix. 
Add Tally program/preview for mix1 for some input. Put it in main program/preview 
Change  program sourses of additional mixes.
Tally feedback flashes. Also related variables flashes (changing) too.

**Expected behaviour**
No flashing tally

**System (please complete the following information):**

- Companion Version 3.3.1
- vMix version [26.00.45]

**Comment by thedist** [comment]
I've just released a fix and it will be merged with the next Companion Beta release later today, and with the next Companion Stable release when the next one is ready in the near future.
