### ISSUE TITLE
Feedback bug with list's

### ISSUE THREAD

**Issue by McHauge** [bitfocus/companion-module-studiocoast-vmix#28]
There is a current bug with feedbacks, that happens when you have an empty list in the inputs.
When you have an empty "list" all feedback breaks, this has to do with how the API is read when an empty list is present.

take a look at this printout: 
(with 2 inputs and an empty list)
`<vmix>
<version>23.0.0.54</version>
<edition>Trial</edition>
<inputs>
<input key="9f38c242-ef98-49e6-a554-1598e8baabe3" number="1" type="Colour" title="Colour" shortTitle="Colour" state="Paused" position="0" duration="0" loop="False">Colour</input>
<input key="20d20c99-e9f4-4abf-a0ea-48fb1e371c12" number="2" type="Colour" title="Colour" shortTitle="Colour" state="Paused" position="0" duration="0" loop="False">Colour</input>
<input key="c64e9f86-b361-481c-abfb-386a04e5b76f" number="3" type="VideoList" title="List" shortTitle="List" state="Paused" position="0" duration="0" loop="False" muted="True" volume="100" balance="0" solo="False" audiobusses="M" meterF1="0" meterF2="0" selectedIndex="0">
List
<list/>
</input>
</inputs>
<overlays>
<overlay number="1"/>
<overlay number="2"/>
<overlay number="3"/>
<overlay number="4"/>
<overlay number="5"/>
<overlay number="6"/>
</overlays>
<preview>2</preview>
<active>1</active>
<fadeToBlack>False</fadeToBlack>
<transitions>
<transition number="1" effect="Fade" duration="500"/>
<transition number="2" effect="Stinger1" duration="1000"/>
<transition number="3" effect="Wipe" duration="1000"/>
<transition number="4" effect="CubeZoom" duration="1000"/>
</transitions>
<recording>False</recording>
<external>False</external>
<streaming>False</streaming>
<playList>False</playList>
<multiCorder>False</multiCorder>
<fullscreen>False</fullscreen>
<audio>
<master volume="100" muted="False" meterF1="0" meterF2="0" headphonesVolume="100"/>
<busA volume="100" muted="False" meterF1="0" meterF2="0"/>
<busB volume="100" muted="False" meterF1="0" meterF2="0"/>
</audio>
</vmix>`

(with 2 inputs and a non-empty list)
`<vmix>
<version>23.0.0.54</version>
<edition>Trial</edition>
<inputs>
<input key="9f38c242-ef98-49e6-a554-1598e8baabe3" number="1" type="Colour" title="Colour" shortTitle="Colour" state="Paused" position="0" duration="0" loop="False">Colour</input>
<input key="20d20c99-e9f4-4abf-a0ea-48fb1e371c12" number="2" type="Colour" title="Colour" shortTitle="Colour" state="Paused" position="0" duration="0" loop="False">Colour</input>
<input key="c64e9f86-b361-481c-abfb-386a04e5b76f" number="3" type="VideoList" title="List - Frontrow_Baggrund.png" shortTitle="List" state="Paused" position="0" duration="0" loop="False" muted="True" volume="100" balance="0" solo="False" audiobusses="M" meterF1="0" meterF2="0" selectedIndex="1">
List - Frontrow_Baggrund.png
<list>
<item selected="true">C:\Users\mc-ha\OneDrive\6_VMIX_Setups\Frontrow - Logo\Frontrow_Baggrund.png</item>
</list>
</input>
</inputs>
<overlays>
<overlay number="1"/>
<overlay number="2"/>
<overlay number="3"/>
<overlay number="4"/>
<overlay number="5"/>
<overlay number="6"/>
</overlays>
<preview>2</preview>
<active>1</active>
<fadeToBlack>False</fadeToBlack>
<transitions>
<transition number="1" effect="Fade" duration="500"/>
<transition number="2" effect="Stinger1" duration="1000"/>
<transition number="3" effect="Wipe" duration="1000"/>
<transition number="4" effect="CubeZoom" duration="1000"/>
</transitions>
<recording>False</recording>
<external>False</external>
<streaming>False</streaming>
<playList>False</playList>
<multiCorder>False</multiCorder>
<fullscreen>False</fullscreen>
<audio>
<master volume="100" muted="False" meterF1="0" meterF2="0" headphonesVolume="100"/>
<busA volume="100" muted="False" meterF1="0" meterF2="0"/>
<busB volume="100" muted="False" meterF1="0" meterF2="0"/>
</audio>
</vmix>`

Take a look at the missing start bracket for the list, or you could say the extra stop bracket in the setup with an empty list

same setups but as pictures here:
(with 2 inputs and an empty list)
![image](https://user-images.githubusercontent.com/31018035/86277498-14d3a980-bbd7-11ea-9e0a-f4676e5870da.png)

(with 2 inputs and a non-empty list)
![image](https://user-images.githubusercontent.com/31018035/86277461-04233380-bbd7-11ea-9932-642f8ef8a6f9.png)

**Comment by Toddric** [comment]
Bug still exists in 2.1.0-47823d0-2493 Release

**Comment by McHauge** [comment]
> Bug still exists in 2.1.0-47823d0-2493 Release

yes is does, and it's reproducible all the time,

**Comment by krocheck** [comment]
What is the error?  `<list/>` is not technically valid to XML specification (although is valid XHTML markup), however there are a ton of other cases of tags using the trailing slash 'void' or 'singleton' annotation, such as `<overlay number="4"/>`.

**Comment by McHauge** [comment]
@krocheck tottaly true, I mis read the xml,, but the module's feedbacks kinda freezes where there is no "item" in the xml. So that's where the real problem is.

**Comment by krocheck** [comment]
`api.js`
```javascript
if (input.list) {
	data.list = input.list[0].item.map((item, index) => {
		const location = typeof item === 'string' ? item : item._;
		return {
			index,
			location,
			filename: location.split('\\')[location.split('\\').length - 1],
			selected: item.$ && item.$.selected && item.$.selected === 'true'
		};
	});
}
```

Have you tried `if (input.list && input.list.length > 0) {`?

**Comment by McHauge** [comment]
@krocheck not yet but will in a minute 😅, tried something similar but wasn't successful. Not that use the work with xml yet

**Comment by McHauge** [comment]
I'll close this, since it should now be fixed in new releases of the beta branch of Companion.
and thx @krocheck for the push in the right direction.
