### ISSUE TITLE
Request: Get selected index of list

### ISSUE THREAD

**Issue by Coupe70** [bitfocus/companion-module-studiocoast-vmix#281]
**Describe the feature**
Some way to get the selected index of a list.

**Is this version dependent (vMix v24.)?**
don't think so

**Usecases**
I read here on github that there once was a variable ${vmix:input_<GUID, Number, or Name>_selected}.
That's exactly what I need, but it seems to be gone in 3.3.1
I also read here that at some point variables had to be killed for performance reasons which is a pity as I 
don't need ANY of the available variables, I just need this one.
Any chance to bring it back? Or to bring in any feature (action/feedback/trigger) to pull this value from the API 
to a custom variable? Or maybe a generic feature to define a certain value to be pulled from the API?
Or - last and maybe more complex idea - some kind of configuration to choose which variables will be available 
in the vmix module? That way everyone could choose which variables he needs and could turn off the rest for
better performance.

Just in case it is already there and I'm missing something:
I know there is the 'Toggle which variables are shown in the Instance Variables List' configuration in module setup
and I have 'Input Variables by GUID' etc all on and 'Limit Input Variable Types' off, but I still don't see what I need.

**Comment by thedist** [comment]
`$(vmix:input_<GUID, Number, or Name>_selected)` is still in the Companion module, as is all variables that were previously available, nothing has been removed.

What is changed is that we now have config options `Input Variables by Name`, `Input Variables by Number`, and `Input Variables by GUID`. Toggling these on/off will either show or hide those variables from auto-complete.

There's also the config option `Limit Input Variable Types - Toggle on to not only hide certain input variables from auto-complete but disable their use. May improve performance when enabled` which when toggled on will not only hide those previously hidden variables from auto-complete, but will also remove it from being defined whatsoever so wont be usable.

So what I would suggest is checking your config, making sure you have it set so however you wish to reference inputs (name, number, or guide) is enabled, and then check again and you should be able to use that selected variable.

**Comment by Coupe70** [comment]
@thedist 
I'm sorry, I just edited my post above.
I know there is the `Toggle which variables are shown in the Instance Variables List` configuration in module setup
and I have `Input Variables by GUID` etc all on and `Limit Input Variable Types` off, but I still don't see what I need.

All I get when typing `$(vmix:inp` is vmix:input_any_solo.

**Comment by thedist** [comment]
What happens if you fully type out the variable and not use auto-complete? For example if you had an input named 'list' and put `$(vmix:input_list_selected)` as button text, does it show `$NA` or does it show a number?

**Comment by Coupe70** [comment]
Or is it maybe because I'm just having a look without really being connected to a vmix instance?
But the other variables are there...

**Comment by Coupe70** [comment]
I will check tomorrow - maybe it's not working as I am only having a look at the module without being connected to a vmix instance...?

**Comment by thedist** [comment]
If you're not connected to vMix, then there's no way for it to know what GUID, Name, or Numbers, are used for inputs, so it can't create variables with labels and even default values.

Some variables, such as `vmix:input_any_solo` will work regardless of a connection to vMix because it's not dependant on a connection to be created and given a default value, like many other variables that aren't related to specific inputs.

**Comment by Coupe70** [comment]
That makes perfect sense...sorry, probably I was a little fast with my complaint / request.
Was a bit confused because of the old issues stating there were variables removed.
I'll report back tomorrow after testing with the real setup.

**Comment by Coupe70** [comment]
You were absolutely right. With a real vMix connection all variables are there.
Thanks for explaining and for your time!
