### ISSUE TITLE
Variable of title with name not layer titletext

### ISSUE THREAD

**Issue by semenovnick** [bitfocus/companion-module-studiocoast-vmix#284]
**Describe the feature**
It will be cool, if threre will be switch how to get variables of _titletext_ from **index** to **name** part of xml node. Now it is only by index. 
For example:
```js
$(vmix:input_mytitle_layer_txt_field1_in.text_titletext)
```
**Is this version dependent (vMix v24.)?**
I think, no

**If documentation is required to implement, do you know where to find it?**
The title node of input in XML has **text** node:
```xml
<input key="8e9ac875-775b-4f7f-8eaa-d4a61f9c2796" number="31" type="GT" title="MYTITLE" shortTitle="MYTITLE" state="Running" position="0" duration="0" loop="False" selectedIndex="0">
OL5
<text index="0" name="txt_field1_in.Text">Kirill Kirillov</text>
<text index="1" name="txt_field2_in.Text">Guest from Nikaragua</text>
<text index="2" name="txt_info.Text">GUEST 1</text>
</input>
```
And it's node has two attributes: **_index_** and **_name_**
**Usecases**
I use titles as storage for some properties. And it s difficult to use only indexes because if i have many text fields it s difficult to work with/ For example I have some title with properties of knob for companion: color, name, layer etc... for 32 inputs... To get property of layer i mist get {32*3+inputNumber} index... 
Thanks's a lot!

**Comment by thedist** [comment]
The latest update now includes a `input_X_layer_NAME_titletext` variable. Keep in mind though that certain special characters in the name may be invalid as a variable id, and so might now work as currently I haven't implemented anything to try to manipulate the text field to something that is valid as that may be confusing for end users and I'm also hoping most people use appropriate naming schemes when making titles that wouldn't use special characters in the names.
