### ISSUE TITLE
Error with presets

### ISSUE THREAD

**Issue by stevespaw** [bitfocus/companion-module-studiocoast-vmix#29]
I get this error when I have added some of the utility presets like streaming. They work in my local project, but when I save the config and move it to another PC. I get this: 
![image](https://user-images.githubusercontent.com/11045430/86837455-9195d600-c064-11ea-94a0-cc7332a2669b.png)

**Comment by McHauge** [comment]
@stevespaw thanks for the info, what version of Companion. I would expect that you are on one of the 2.0 builds. Because over the last month or two there has been quite a few updates to the module.

**Comment by stevespaw** [comment]
Yes that is with one of the newer builds from a couple of weeks ago. I will try again with newer builds and report back
