### ISSUE TITLE
Action "vmix: Layer - Position" doesn't work

### ISSUE THREAD

**Issue by DannyGudkov** [bitfocus/companion-module-studiocoast-vmix#290]
**Describe the bug**
Action "vmix: Layer - Position" doesn't work.
I tried this action on couple pc with different companions and vmix's. 
Tried all types of settings and adjustments available as well as different types of values for the adjustment. Need to notice that action Input - Position works fine. In the attachment you can see log where debug message is sent when Input - Position action pressed and nothing is sent when Layer - Position is pressed. Same happens with release action.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'edit button'
2. Click on 'press or release action or use presets to add Layer - Position function'
4. Set desirable input and layer, setting to change and adjustment type
5. After pressing the button or pressing Test nothing will happen

**Expected behaviour**
Changing position of layer in input based on setting and adjustment of Press or Release action

**Screenshots**
![Image](https://github.com/user-attachments/assets/e88b3686-3b46-4c24-b19e-1e8cd24be95b)
![Image](https://github.com/user-attachments/assets/384ff79e-6872-4e79-ad0c-c76eb705ac49)

**System (please complete the following information):**

- Companion Version [3.4.2] and [3.5.0]
- vMix version [26.0.0.45] and [27.0.0.87]

**Additional context**

Want to say thank you to all contributors of this module, you've made usefull and reliable feature. Hope this issue will be easy to fix or maybe or it will turn out that I'm doing something wrong and if so i really need some help from the community because I tried everything i can think of to make it work.
Thanks in advance!

**Comment by thedist** [comment]
Thanks for the report. I've found the issue, it appears to be due to how layers are handled when there's there's some missing (eg, there's a layer 3 but not a layer 2 or layer 1).

I'll have a fix rolled out shortly that should be in the betas later today.

**Comment by thedist** [comment]
This should now be fixed in the latest Beta builds. Also, keep in mind that the Layer Positioning functions were added in vMix 27, so will not function in versions of vMix prior to that.

**Comment by DannyGudkov** [comment]
That was really quick, thank you so much. Waiting for release to check.

**Comment by thedist** [comment]
The latest Companion release, v3.4.3, should include this update to the vMix module.
