### ISSUE TITLE
Add separate mono actions and feedback

### ISSUE THREAD

**Issue by patmu** [bitfocus/companion-module-studiocoast-vmix#292]
**Describe the feature**
It's possible to set an input to audio "SeperateMono" mode. I would like to see the following features for this mode:
- Implementation of actions "SetVolumeChannel1" and "SetVolumeChannel2" to control the channels volume independently (action).
- Implementation of single channel volume meter, assignable to channel 1 or channel 2 of an input (feedback). Like the existing one, but only with one meter.
- Implementation of variables "volume linear" and "volume db", assignable to channel 1 or channel 2 of an input (feedback). Like the existing ones, but only with the value of the selected channel.

**Is this version dependent (vMix v24.)?**
No

**If documentation is required to implement, do you know where to find it?**
https://www.vmix.com/help27/ShortcutFunctionReference.html
Feedback about volume level is provided in the xml api: volumeF1="1" volumeF2="1" 
Feedback about meters is provided in the xml api: meterF1="0.1160889" meterF2="0.1160889"

**Usecases**
My use case: I have commentators coming in, commentator 1 on left channel and commentator 2 on right channel of a stereo interface/input. Putting the audio input into "SeperateMono" mode I can control the volume individually.

Thank you for considering.

**Comment by thedist** [comment]
The latest update to the module now includes a `Audio - Set Input Channel Volume` Action, `input_X_volume_f1`, `input_X_volume_f1_db`, `input_X_volume_f1_linear`, `input_X_volume_f2`, `input_X_volume_f2_db`, `input_X_volume_f2_linear` Variables, and the `Audio - Input Volume Meters` feedback now supports a single channel meter.

This update is currently in the latest Companion Beta builds.
