### ISSUE TITLE
vmix: Video - Video Timer Feedback not Displaying

### ISSUE THREAD

**Issue by richardhargrave** [bitfocus/companion-module-studiocoast-vmix#294]
Hello , When I select the Video timer feedback option - the button just shows blank - It used to work on a previous version .

**Comment by thedist** [comment]
That's not a bug. The feedback was changed almost 2 years ago.

It now just change the text colour as the text can be controlled better through variables such as `input_X_remaining`, where `X` is the inputs name, number, or GUID. This also means you can use Expression Functions to manipulate the time remaining into different formats, eg ms, mm:ss, ss.ms, etc., as well as have more dynamic text in addition to the timer.
