### ISSUE TITLE
Vmix 28 stream active value for 4 and 5 destination

### ISSUE THREAD

**Issue by nikosman88** [bitfocus/companion-module-studiocoast-vmix#300]
**Describe the bug**
Hello. Im trying the version 3.7.0 in vmix 28.0.24 in companion beta 3.5.0.7598 and i enable the 4 or 5 stream destination. But in companion variables it doesnt appear as variable stream_4_active and stream_5_active
Thanks

**Comment by thedist** [comment]
That's already known as a bug, and it just impacts variable definitions, the actual variables themselves still work it just wont show in auto-complete

**Comment by thedist** [comment]
This should now be resolved in the latest Companion beta builds.
