### ISSUE TITLE
Title Preset Index

### ISSUE THREAD

**Issue by fill30** [bitfocus/companion-module-studiocoast-vmix#33]
In Companion when using "vmix: Title - Select Title Preset", I am unable to find what the preset index is for a title layer. Could you help me?

**Comment by McHauge** [comment]
when you use a GT title, then you can create presets for it by adding the text to the layers and clicking the "plus" button on the title, to use them with companion they start from the top down, in the order, you have them in the title editor. starting with the top being "0" and the next "1", next "2", and so on. hope it helps
