### ISSUE TITLE
Vmix audio feedback to Icon

### ISSUE THREAD

**Issue by hadphild** [bitfocus/companion-module-studiocoast-vmix#35]
Is there any way companion can have a preset to get the db rating from an audio bus. 

Just say the top part of the icon is the peaking number and the bottom text is current.

IE 

-6 db 
-18 db 

Chnaging colour if its clipping.

**Comment by McHauge** [comment]
@hadphild I have added a feedback for both inputs and bus's that does something similar to this. if added to a button you will find the text matching the VU volume bar in vmix, and an option to show the current dB value on the button. This function will be added shortly to the main branch beta builds.

Hope this will help.

**Comment by McHauge** [comment]
did not mean to close this yet, ups. just reopen if this you have a comment or two.

If you are on windows then you can go the link below and download one of my beta/dev builds to test it out today.

[Onedrive (Download)](https://1drv.ms/f/s!AtUYbExJseNtlK56u-n71V_UcLDe7g)

**Comment by hadphild** [comment]
Could you make it so I can have a peak and current db. 

Also traffic light for DJ mode.

**Comment by hadphild** [comment]
If the button had 

Peak      -6db
Current -12db

**Comment by McHauge** [comment]
Not currently, have a more important problem first, but feel free to add it

**Comment by hadphild** [comment]
Thank you for the amazing plugin as well. You are a credit to the community

**Comment by hadphild** [comment]
What other issues have you got

**Comment by McHauge** [comment]
The two bugs with moving a setup, and the fact that I need to think of a way to do it without using a ton of code for when you have a lot of inputs

**Comment by McHauge** [comment]
Have you tried the build I linked? And seen it in practice

**Comment by hadphild** [comment]
I will get later tonight. Looking forward to it. Just got to get the little one to bed
