### ISSUE TITLE
adjustable HTTP GET frequency

### ISSUE THREAD

**Issue by jpyle490** [bitfocus/companion-module-studiocoast-vmix#37]
This is on Companion 2.1.0 (47823d0-2493) running on Windows 10, and the version of the module included with its installation.

I've been tracking an audio glitchiness issue in vMix, and I've tracked it down to the frequency of HTTP GET requests this module sends: 10/sec.  I've ruled out everything else.  When this module rules, I incur audio drops with increasing frequency over time.  When it doesn't, all clean.  This is on a Ryzen 4 3950X 16-core @ 4 GHz CPU with 32 GB of RAM with vMix running a handful of inputs at 720p60.  Horsepower isn't an issue.  I've also noticed 'fullscreen' drops, although those I care much less about.

I've started a conversation with vMix about the problem since it appears their API thread is blocking in some way.  If I crank up the request frequency with a curl script, I can push the whole CPU to 100%.  That's not good.

In the meantime, it would be fantastic if there were an option to adjust the frequency of the GET requests from the module, or to disable them altogether.  My particular configuration only sends commands to vMix and doesn't make use of any of the data returned from it.  To work around the problem I've pointed this module at a local nginx server on Linux to return a static XML file with enough data to satisfy the HTTP GET, and configured a double-NAT in iptables to point the TCP API port back to the real vMix server.  Desperate times call for desperate measures I suppose.

**Comment by jpyle490** [comment]
vMix confirms the HTTP API should only be polled once or twice per second.  Anything beyond that could cause issues depending on how many inputs it has to report on, etc.

**Comment by McHauge** [comment]
Could add a drop down for low/mid/high pool rate in the einstance config, that would coralate to 0.1/0.5/1 sec. For simple selection.

**Comment by krocheck** [comment]
@McHauge if the manufacturer is saying only 500ms or 1000ms polling intervals it serves that we should not be exceeding that here just because we feel like it.  I would suggest a dropdown of the options: .5/1/2/disable.

**Comment by thedist** [comment]
The reason I've set the poll rate to what it currently is (100ms) is that this is the rate myself and other developers working with vMix (even prior to Companion being a thing) found suitable in terms of performance and responsiveness. Not only that but there are some features that are reliant on expediency of data from the API, such as the Video Timer feedback which countsdown the time remaining on a video with 0.1s accuracy.

It's certainly possible I could add an option to adjust, or even disable, polling of the API for less capable machines or for situations where it is not required.
