### ISSUE TITLE
tries to connect when disabled

### ISSUE THREAD

**Issue by jpyle490** [bitfocus/companion-module-studiocoast-vmix#38]
After I've been using the module for a while, I disable the it but it continues to try to connect.  In this case it fails because vMix is no longer running.

![Screenshot_20200825_001550](https://user-images.githubusercontent.com/5225183/91122435-56795180-e668-11ea-9816-74b99b4777a6.png)

It doesn't always do this.  For example, after restarting Companion fresh, enabling, then disabling the module, it looks normal.  It only seems to happen after I've been using it for a while.  I don't have a firm grip on the pattern yet.

**Comment by McHauge** [comment]
Hi, and thx for the heads-up. Depending on what version you are running, this might be coralated with an empty list. Not sure about that but that have given some problems before. But that should be fixed in new beta releases after the next version pull, but this error might still exists.

**Comment by jpyle490** [comment]
An empty list...of what?  Is this a configuration item I can fix, or a coding item I cannot?

**Comment by McHauge** [comment]
@jpyle490 the empty list thing, is if you have an empty "list" as an input in Vmix, just add a placeholder video to the "List" input and it will be fine, but not sure if this affects this bug.

**Comment by jpyle490** [comment]
@McHauge the only list input I have has audio files in it.  Not empty, but no video files either.  This particular problem seems to occur subjectively after this plugin has been running and doing things for a while.  The debug logs in Companion don't offer much, either, just that it's been disabled, but then fails to connect.

**Comment by McHauge** [comment]
@jpyle490 When you say "for a while" are we talking like an hour, 10 hours, a day or more? it's not recommended at the moment to run companion for multiple days without a restart, there is a current bug about it crashing over multiple days/weeks.

**Comment by jpyle490** [comment]
@McHauge Good question, I'd say in the few-hours region.  It's been a very subjective thing.  I'll pay closer attention to when it does and does not try to reconnect when disabled to see if I can isolate a trigger, or at least rule out some.

**Comment by josephdadams** [comment]
@McHauge we just got that fixed where it crashes after a long time! @onfire4g05 fixed it!

**Comment by McHauge** [comment]
gonna close this, if it still happens then feel free to open it up again
