### ISSUE TITLE
Getting erratic behavior with certain functions within vMix now.

### ISSUE THREAD

**Issue by jjbutler83** [bitfocus/companion-module-studiocoast-vmix#40]
Have had Companion/Stream Deck/vMix successfully playing nice for some time now. However, now I am getting erratic behavior in regards to toggling the external output off/on and the FTB/fade to black toggle as well, the button programming behavior seems different as well and only works when I set the button as a toggle in Companion, something that I did not have to do previously. Companion is running on a Pi 4B - version 2.1.1 (75d6797-2537)- 

Thank you.

**Comment by thedist** [comment]
This should be resolved by #39 so try the latest build and check to see if you're still having issues.

**Comment by jjbutler83** [comment]
Thank you.

I did update my Companion Pi machine yesterday and all of the weirdness does now seem to be resolved.

Thanks!

-J
