### ISSUE TITLE
Instance Feedback: Live Input in program/preview

### ISSUE THREAD

**Issue by swperic** [bitfocus/companion-module-studiocoast-vmix#41]
I am not sure if this should be a modification to the existing feedback function or a separate type of feedback.  I would like to be able to set feedback on a button if any input on a multi view input is in the preview/program.  I believe the tally natively works that way so maybe that could be how a new function works.  Tally is Program (set input name) and Tally is Preview (set input name).  Thanks for reading!

**Comment by thedist** [comment]
It would have to be a separate feedback and not a modification to the existing one as the way the current feedback works is how it's given by the vMix API, and also how everyone is used to having it.

There is also a limitation in that there's no differentiation between Input, MultiView, or Overlay, in preview/program, It's an all or nothing type thing so you couldn't have a deep red for input that's live, and an off-red for all multiviews/overlays that are part of that, they would all just be red. Secondly, there's no API support for this sort of things in Mix 2 to 4, only Mix 1 could use this feedback.
