### ISSUE TITLE
replay play to out

### ISSUE THREAD

**Issue by PTS-mediacube** [bitfocus/companion-module-studiocoast-vmix#46]
the companion module does not have ReplayPlaySelectedEventToOutput and ReplayPlayEventsByIDToOutput functions.
can you add these features?

**Comment by McHauge** [comment]
@PTS-mediacube Hi, this should be added to the module now, I'll do a test later today, and if that goes well get it qued up for getting it included in the core. so expect it to be available in new beta build's in 3-5 days.

**Comment by thedist** [comment]
Just for future reference, there are lots of functions not natively available as actions within this module and that was my design choice as there are far too many niche functions to include them all. As explained in the help file there is a link to a vMix Function Cheat Sheet I released https://util.dist.dev/vmixapi which is a complete list of functions, all of which can still be used within the vMix instance as custom commands.

**Comment by McHauge** [comment]
think this got solved with the adition of both, so I'm closing this
