### ISSUE TITLE
vMix get unstable / generate audio - video drops if using Companion

### ISSUE THREAD

**Issue by schoeoefli** [bitfocus/companion-module-studiocoast-vmix#48]
For some time now I noticed that vMix runs unstable or after several hours of events dropped frames and generates audio peaks. 

problem: 
- When using Companion (also externally on another system and only linked via network), frame drops or audio glitches occur after 1 hour of show. 
- If two independent Companion clients are used in the same network, the drops / glitches are much worse. 
- During a show the USB audio interface was lost.
- At one show it crashed vMix. 
- The problem occurs on different systems with different vMix versions. 

My current solution search. 
- Set up new windows
- test with ASIO driver from Steinberg and Focusrite and without
- Test with independent network 
- Test with other network cables
- Test with other NIC (USB to ethernet adapter)
- Test with different performance levels (complexity projects)
- Test with last version v.2.1.1
- Test with vMix 23.0.0.62 and newer
- Using various older Blackmagic Video drivers.

Conclusion:
- When I use Companion, I already have the first drops after 1 hour on all systems with the current version v2.0.1.
- After a reboot the system runs stable for about 1h. Systems that have been online for 24 hours have a much higher number of drops.
- Systems without Companion run for up to 14 hours without any drops.
- It does not matter whether the Companion Client runs on the PC or on another computer. (Same problem)

In the attachment I have some pictures of the glitches and a audio file.

https://we.tl/t-8CowvFNIqA

Gladly I will carry out further tests recommended by you. 

Best,
Jan

**Comment by McHauge** [comment]
I would think that a beta builds of v2.1.1 will fix this, since we a pulling the api every 500ms vs every 100ms in companion v2.1.0, this polling rate is also changeable in v2.1.1 so you could try to only pull every 1 second as a test

**Comment by schoeoefli** [comment]
Thanks, on my first test I only had 1 dropped frame after 11 hours of recording. But this drop can be many other things.
I will now test further setups. The current setting is 1000ms.

**Comment by daniep01** [comment]
I have seen similar problems of brief audio disturbances on a livestream which began when I started using companion to control VMix (I was previously using JustMacros with no audio glitch issues). I’m now trying 1000ms polling.

**Comment by schoeoefli** [comment]
@McHauge what was the pulling rate in v1.4.0? In this version I did not have this problem.

**Comment by McHauge** [comment]
@schoeoefli don't think that there are any feedbacks, excepts tally, and therefore no real "polling rate" since tally is being pushed by vmix in 1.4, if I remember it correctly

**Comment by Sam-D03** [comment]
I've never thought or tested to see if companion is the cause, but I AM using companion to control vmix, and I see the EXACT issues you've mentioned in your post. The symptoms include frame drops/audio peaks start after 1 hour of operation.

Running Vmix on EC2 Cloud servers.

**Comment by schoeoefli** [comment]
vMix has just released an update v23.0.0.66 to solve this problem. 
https://forums.vmix.com/posts/t20846-vMix-23-Changelog/page2

Email from Martin: "Essentially the Companion plugin should be using the TCP API to poll for updates using a single connection, which is the recommended method.
Unfortunately for some reason it still appears to be be opening up new connections every time, so at a 200ms update rate that is 18,000 connections per hour which can have an impact on quite a few things potentially. So while we have added a fix on our end, I hope they can make sure to re-use the same connection each time in a future plugin update". 

@McHauge  - maybe there is something for you.

**Comment by schoeoefli** [comment]
vMix has just released an update v23.0.0.66 to solve this problem.
https://forums.vmix.com/posts/t20846-vMix-23-Changelog/page2

**Comment by schoeoefli** [comment]
@McHauge email from Martin:
"Essentially though they should be re-using HTTP and TCP connections where possible instead of creating new connections for every poll."

Could you check this?

**Comment by McHauge** [comment]
@schoeoefli Fell like, at least some of this, might be easier for @thedist to implement/fix or maybe just come with some ideas. Since he is the person who re-wrote the whole back end of the module is a way that made feedback and variables a lot simpler and smarter.

If I remember correctly, then we currently use HTTP to receive all feedbacks/variables, and use TCP to send actions to vmix, but it might be HTTP for both.

**Comment by JeffreyDavidsz** [comment]
It would be poor programming to open new sockets each time. My guess is that's not the case. I can check

**Comment by JeffreyDavidsz** [comment]
So indeed REST get request is done for pulling data. the TCP connection is only one socket. Default polling (sending the get request) is 250ms. I'm reading a poll of 1000ms gives a drop of 1 frame in 11 hours? As its a underlying module that runs the GET request I'm not 100% sure if that socket is being opened all the time. We can program a websocket and make sure that its the same connection all the time? @thedist

**Comment by thedist** [comment]
Just commenting to note I am actively working on this.

Currently we use the `got` lib for HTTP requests (as most other HTTP request libs are based on `request`, which is deprecated) to pull API data used for all feedback. This doesn't natively support keepAlive to maintain a persistent connection, but does support the using a HTTP agent lib to handle that.

What I'm currently benchmarking is if the optimal fix would be to add that additional dependency and continue using HTTP polling. or if polling through the existing TCP connection that is currently used only for sending commands would be more performant.
