### ISSUE TITLE
+ symbol can’t be used in names

### ISSUE THREAD

**Issue by ruudboon** [bitfocus/companion-module-studiocoast-vmix#51]
When having a '+' symbol in a name the input isn't triggered.
Maybe we need to urlencode first?

**Comment by McHauge** [comment]
that, is correct it's curently just a raw text, and would need an URL encoding to work with special characters

**Comment by krocheck** [comment]
@McHauge i think he's suggesting that you should apply a `urlencode` to the input field for sending the action to correct for this.

**Comment by McHauge** [comment]
yes, that is true xD I just confirmed that there is no current encoding, but surely it should be added at some point.

**Comment by McHauge** [comment]
hmm just did some testing, and it seems that it's only some characters that don't work 
Does work: =-_!<>()[]{}@£$€%"#¤ (including spaces)
Does not work: +/&

at least this is what I get from my testing, and I would expect that this is due to the way the commands are made in the vmix api and not due to missing URL encoding. at least this is true in the current builds.

like a & is used to add more parameters and I think + can be used for selecting more than one at a time in some cases.

**Comment by ruudboon** [comment]
Not sure how the vMix api is working but it looks like we are sending a get request and +/& and probably '?' are handled as separaters. If we can urlencode the get params before sending I think it will be resolved.

**Comment by McHauge** [comment]
nope dosent work just tested encoding those, or at least I can't get it to work, also using ' ' or " " around it does nothing except break it

**Comment by McHauge** [comment]
edited the abode, '?' also works currently

**Comment by ruudboon** [comment]
> nope doesn't work just tested encoding those, or at least I can't get it to work, also using ' ' or " " around it does nothing except break it
Hmm weird. I expected that something like 'http://127.0.0.1:8088/API/?Function=Fade&Duration=1000&Input=Speaker%20%2B%20Call' would work if my clip called 'Speaker + Call'.
I got my vMIx machine back on Thursday. I will do some debugging then.

**Comment by McHauge** [comment]
you can try to paste the encoded into the input field, it's weird but that field is just pashed raw through, so... if you find something let us know

**Comment by ruudboon** [comment]
Will get back to you on this on Thursday. Thnx!

**Comment by thedist** [comment]
1 thing to keep in mind when testing, this module sends commands over the TCP connection, not to the HTTP REST endpoint. I'm not sure if this impacts what characters need to be escaped or not though.

**Comment by ruudboon** [comment]
Finally able to setup a development env. This problem can be resolved by wrapping the input(`${opt.input}`) with `encodeURIComponent()`.
I tried this locally and was able to switch input with a "+". 

Looking at the code and vMix docs I think all values needed to be escaped. Preferable I would like to do this in a central place but I think we receive the data from the core and I'm not sure if we can create a hook there. I can write a fix but would like to discuss the implementation first.

**Comment by McHauge** [comment]
Great, feel free to come and join us on slack, we have a dedicated channel for vmix 👍

**Comment by ruudboon** [comment]
OMW
