### ISSUE TITLE
More varibles

### ISSUE THREAD

**Issue by McHauge** [bitfocus/companion-module-studiocoast-vmix#54]
Adding the Variables for what input is live/in preview on a mix and maybe if possible live in an overlay, will help with incorporating controls into the new trigger system and scheduler in the dev branch

Ideas to variables:
- Mix 1-4 preview - done 
- Mix 1-4 Program - done
- Input GUID listed underneath Input names - done
- Variable; Call (Number) is connected - done
- Overlay  1-4 state and input name/nr - done
- Record and stream state - only ON/OFF state possible - done
- Fullscreen and external state - ON/OFF State - done
- Advanced call quality indicator - locked by API?
- Currently on output 1-4 - locked by API?
- ...

but should not be excessive to minimize overloading companion.

**Comment by TreborKutscher** [comment]
Also add the Variable; Call (Number) is connected.

Advanced quality indicator as an variable.

**Comment by McHauge** [comment]
Think all variables, that I had in mind are included now, so I'll close this for now :)
