### ISSUE TITLE
Clean Up Actions

### ISSUE THREAD

**Issue by McHauge** [bitfocus/companion-module-studiocoast-vmix#55]
Clean up old actions that should/could be grouped into one to minimize clutter in the actions drop down, not too sure about the best approach since this will require an update script.

This will also affect presets, that will need to be redone/updated to match.

**Comment by krocheck** [comment]
so long as you track the transforms that need to occur I can work with you on the upgrade script

**Comment by McHauge** [comment]
gave up on this, so closing it for now
