### ISSUE TITLE
Request to be able to fire a VMix MidinoteOn or Off command.

### ISSUE THREAD

**Issue by sweetapollo** [bitfocus/companion-module-studiocoast-vmix#57]
I currently have some shortcuts set to keyboard keys, works great, but also have some that are set to midinote presses. I dont see the o be able to activate these either with a custom code or via key press. Is this something that is possible>

**Comment by TreborKutscher** [comment]
Can you give an example? The most "shortcuts" are predefined as comands in companion for vmix.

I mostly dont us shortcut but use the vMix module and fire the desired command directly from companion without setting soming in vMix

**Comment by sweetapollo** [comment]
So I have a keyboard press shortcut for the key A. I can do this on the companion by using vmix: General - KeyPress with an option of 'A'
I can also fire the same shortcut via the option vmix: Run custom command with the option of 'KeyPress Value=A'

I do have a MIDI interface that will allow a button press on my midi device to activate a shortcut.  These produce a 'MIDINoteOff' key command. Or 'MIDINoteOn' repending if you want the command on the press or release etc.

I have tried a few different ways to make the code work with either the general key press command or custom code command.

I have tried MIDINoteOff1:2 as the command and MIDICC 1:2 and MIDICC1:2 also, but these do not fire.

It might just be a command line or syntax issue, or it might just not work at all and I am wanting something that isn't possible.
<img width="406" alt="Screenshot 2020-11-17 at 19 24 59" src="https://user-images.githubusercontent.com/41735233/99437955-0cbca200-290b-11eb-88b9-cf2fea21bda5.png">
![Screenshot 2020-11-17 at 19 18 13](https://user-images.githubusercontent.com/41735233/99437962-0f1efc00-290b-11eb-9c36-372e3ff448b6.png)

**Comment by TreborKutscher** [comment]
For the given example to launch merge your approach is too complex in my opinion  but it may work if you want to have multi user acces while one operates with keyboard (so you need to map keys in vMix anyway) and one with companion.

to launch merge:
![image](https://user-images.githubusercontent.com/45802233/99442157-3aa8e300-2919-11eb-93e9-3b956ee68d77.png)


For custom macros it gets tricky. 

![image](https://user-images.githubusercontent.com/45802233/99442075-1816ca00-2919-11eb-84fc-2d929cdcbd62.png)


For midi notes try runing https://github.com/josephdadams/midi-relay/blob/master/views/static/logo.png  wich can be spoken to by companion. Its a service that send midi notes.

**Comment by TreborKutscher** [comment]
Space worked for me

**Comment by sweetapollo** [comment]
Hi thanks, Yes maybe what I am wanting is not possible via this route. The examples I gave were just ones I had used for testing. Others do around 8 shortcuts per midi key press, so I was looking for a way to avoid having to clone each command and assign standard keyboard keys or remake them in companion from scratch.

Thanks for your help though!

**Comment by McHauge** [comment]
may I ask what the shortcuts do, because we are mostly limited to what you can do with the vmix "shortcodes"

**Comment by sweetapollo** [comment]
I have around 59-60 shortcuts setup that do anything from change audio buses, change video output assignments for individual callers as well as more basic things like master fader pulls and timer start stop presets. 

Again I could probably do most of them with other things but as they are set for the midi interface I am looking for a way to make them accessible to people who don’t have my remote midi console. The shortcuts are also nice as they are as they give me feedback with the activators built in so I get feedback in my midi device as to what is active or a state change.

**Comment by thedist** [comment]
vMix doesn't have a function for getting it to send MIDI messages. If you want to send MIDI messages then just send MIDI messages yourself with a MIDI module, or proxying through a service on the machine that you want to output those messages.

**Comment by sweetapollo** [comment]
Thankyou so much. I suppose I just need to not be lazy and reallocate all the shortcuts for a different device and create a template. I appreciate you helping me.
