### ISSUE TITLE
V Mix Use imput name or ID as well as number 

### ISSUE THREAD

**Issue by henny19** [bitfocus/companion-module-studiocoast-vmix#6]
when sending commands to vmix would it be possible to use input name rather than the number as i have a production with approx 300 inputs open and things get moved around so input numbers don't stay the same but names do..  

Also whats the chances of Companion pulling in the list of input names from the xml in the  api at :8088/api/

thanks

**Comment by McHauge** [comment]
In v1.1.3 of this module (pull request atm) I have enabled the option to choose whether or not to use ID's or Titles/Names to select inputs. The dropdown idea is a good idea, just not within my skill set yet.
