### ISSUE TITLE
Selected Item Feedback

### ISSUE THREAD

**Issue by TinyCrafter** [bitfocus/companion-module-studiocoast-vmix#64]
I don’t know if this is the correct location (not a github person)...

Feature request for a feedback that checks the api tag selectedIndex of an input. (Specifically for type=“VideoList”,` GT doesn’t seem to report an index)

**Comment by thedist** [comment]
Yes, this is the correct place for Feature Requests :)

Just so I understand, do you want to be able to have a feedback where you select an index and  when that specific index is selected it changes text/colours, or do you want feedback to show which index is selected (eg, have it display 1, 2, 3, or the title of the selected list item) that changes the button as the selection changes?

**Comment by estilles** [comment]
> Yes, this is the correct place for Feature Requests :)
> 
> Just so I understand, do you want to be able to have a feedback where you select an index and when that specific index is selected it changes text/colours, or do you want feedback to show which index is selected (eg, have it display 1, 2, 3, or the title of the selected list item) that changes the button as the selection changes?

Hey @thedist, I know @TinyCrafter hasn't replied, but I have an upcoming event that will need this. along with a few other `selectedIndex` related features. This is what I need:

- an action to select the first, last, next, previous or specific item from a List input
- feedback to change text/color when specific index is selected
- display index/title of selected index

I have some extra time on my hands, would you mind if I take a crack at this?

**Comment by McHauge** [comment]
@estilles for an item list, these two actions selects the next/previos file
![image](https://user-images.githubusercontent.com/31018035/104306762-a1d4b500-54ce-11eb-9054-3e1819ad2bfe.png)

**Comment by McHauge** [comment]
you can also use the short title for the input to show what item is selected, but a separate variable could also be an options yes: 
![image](https://user-images.githubusercontent.com/31018035/104307006-f8da8a00-54ce-11eb-8ee2-0bb145c41e2f.png)

**Comment by estilles** [comment]
> @estilles for an item list, these two actions selects the next/previos file
> ![image](https://user-images.githubusercontent.com/31018035/104306762-a1d4b500-54ce-11eb-9054-3e1819ad2bfe.png)

Ahhhh ... didn't realize "Picture/Slides" referred to a list. (Should've just read the code)

**Comment by McHauge** [comment]
it doesn't directly, it was added to go though slides in powerpoints, but it's the same command as for lists, so... I have a feeling that the shortcode for selecting a specific slide would work for lists too. but I'll have to give it a test, also I'll update the name of those two to be more explanatory :)

**Comment by estilles** [comment]
> you can also use the short title for the input to show what item is selected, but a separate variable could also be an options yes:
> ![image](https://user-images.githubusercontent.com/31018035/104307006-f8da8a00-54ce-11eb-8ee2-0bb145c41e2f.png)

Cool. I would prefer it if it didn't include the title List input name, but that works. Thanks! Is there one for the index as well?

**Comment by McHauge** [comment]
> > you can also use the short title for the input to show what item is selected, but a separate variable could also be an options yes:
> > ![image](https://user-images.githubusercontent.com/31018035/104307006-f8da8a00-54ce-11eb-8ee2-0bb145c41e2f.png)
> 
> Cool. I would prefer it if it didn't include the title List input name, but that works. Thanks! Is there one for the index as well?

not atm, but I'll give it a look. BRB in 15min

**Comment by estilles** [comment]
> it doesn't directly, it was added to go though slides in powerpoints, but it's the same command as for lists, so... I have a feeling that the shortcode for selecting a specific slide would work for lists too. but I'll have to give it a test, also I'll update the name of those two to be more explanatory :)

It works! Thanks.

**Comment by estilles** [comment]
So, I guess we're back on the feedback. Do you guys mind if I work on a quick PR for the feedback on selected index?

**Comment by McHauge** [comment]
if you have it ready go ahead, I'll give it a look, even have vmix on my machine for testing right now

**Comment by estilles** [comment]
How about an action to select a specific index? Would you guys be open to that?

**Comment by McHauge** [comment]
have it done in 2 min

**Comment by estilles** [comment]
Cool ... Thanks!

**Comment by McHauge** [comment]
did you add the variable and feedback or shall I give it a go

**Comment by estilles** [comment]
I haven't yet ...

**Comment by McHauge** [comment]
![image](https://user-images.githubusercontent.com/31018035/104309255-26750280-54d2-11eb-94bb-27238ac7a84a.png)

**Comment by estilles** [comment]
Perfect!

**Comment by McHauge** [comment]
the feedback and variables will have to wait until I get home, just got a call xD

**Comment by estilles** [comment]
> the feedback and variables will have to wait until I get home, just got a call xD

 I can take care of it. I don't mind at all.

**Comment by McHauge** [comment]
> > the feedback and variables will have to wait until I get home, just got a call xD
> 
> I can take care of it. I don't mind at all.

you will have to take look the API.js too, as it currently skipped the list part, do to the bug with empty lists, and I haven't had the time yet to look at it properly.

**Comment by estilles** [comment]
Will do! Thanks for the heads up.

**Comment by McHauge** [comment]
I'll close this sine the merge has been implementet
