### ISSUE TITLE
Vmix tally 

### ISSUE THREAD

**Issue by zorangr** [bitfocus/companion-module-studiocoast-vmix#65]
i was wondering do you have similar issue with tally. When I have set blank or color as input in vmix, tally works ok, but if I set Blackmagic capture device input (DeckLink Duo (1) 1, DeckLink Duo (2) 2, etc...), or i set video file as input, tally does not work anymore. I use vmix 22, and companion 2.1.0

**Comment by thedist** [comment]
I don't have old versions of vMix available to me at the moment so can't test if this may be something to v22, but a couple things to check:

Ensure that the feedback Is correctly pointing to the input (either by index or name), if you're sure that it's set correctly can you take a picture of the feedback settings for the button that isn't working, and also a copy and paste what the vMix API (http://localhost:8088/api) is showing after you've added the inputs that aren't returning feedback

**Comment by zorangr** [comment]
Hi thedist,

indexes are set correctly I think, i have only 4 inputs, so indexes are set 1, 2, 3 and 4. This is API 

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<vmix>
<version>22.0.0.66</version>
<edition>Pro</edition>
<preset>D:\Vmix\4-Cam-IN.vmix</preset>
<inputs>
<input key="55a8f24b-2df0-4b5a-9af5-f20f8974c695" number="1" type="Capture" title="DeckLink Duo (1) 1" state="Running" position="0" duration="0" loop="False" muted="True" volume="100" balance="0" solo="False" audiobusses="" meterF1="0" meterF2="0">DeckLink Duo (1) 1</input>
<input key="e9454745-b67c-414c-b699-b54197ce292b" number="2" type="Capture" title="DeckLink Duo (2) 2" state="Running" position="0" duration="0" loop="False" muted="True" volume="100" balance="0" solo="False" audiobusses="" meterF1="0" meterF2="0">DeckLink Duo (2) 2</input>
<input key="95f73d21-cae3-479d-875b-10f2e8c1cadf" number="3" type="Capture" title="DeckLink Duo (3) 3" state="Running" position="0" duration="0" loop="False" muted="True" volume="100" balance="0" solo="False" audiobusses="" meterF1="0" meterF2="0">DeckLink Duo (3) 3</input>
<input key="cd943171-5b6f-47f7-b0ba-4c0cee7f02db" number="4" type="Capture" title="DeckLink Duo (4) 4" state="Running" position="0" duration="0" loop="False" muted="False" volume="100" balance="0" solo="False" audiobusses="M" meterF1="0" meterF2="0">DeckLink Duo (4) 4</input>
</inputs>
<overlays>
<overlay number="1"/>
<overlay number="2"/>
<overlay number="3"/>
<overlay number="4"/>
<overlay number="5"/>
<overlay number="6"/>
</overlays>
<preview>2</preview>
<active>2</active>
<fadeToBlack>False</fadeToBlack>
<transitions>
<transition number="1" effect="Fade" duration="300"/>
<transition number="2" effect="Merge" duration="1000"/>
<transition number="3" effect="Wipe" duration="1000"/>
<transition number="4" effect="CubeZoom" duration="1000"/>
</transitions>
<recording>False</recording>
<external>False</external>
<streaming>False</streaming>
<playList>False</playList>
<multiCorder>False</multiCorder>
<fullscreen>False</fullscreen>
<audio>
<master volume="100" muted="False" meterF1="0" meterF2="0" headphonesVolume="0"/>
</audio>
</vmix>`

[url=https://ibb.co/6yHTPTS][img]https://i.ibb.co/6yHTPTS/Screenshot-12.png[/img][/url]  this is image from companion setup

**Comment by thedist** [comment]
I don't see anything immediately obvious as being an issue. One thing you could try is update to a newer version of Companion as there have been some updates to the vMix module, then recreate the buttons. If the feedback still isn't working correctly after that try use the input name, or the id (shown as the `key` param for the input if you go to the API page).

**Comment by zorangr** [comment]
I have tried 2.1.1 version but i get javascript errors, like it is unable to communicate with vmix via tcp port 8099. I have tried input key and name, but it does not work either. 

Interesting, when source is set to blank, oro color, tally works ok

**Comment by zorangr** [comment]
This is java script error when i try to use version 2.1.1 or 2.1.2

https://ibb.co/w0Z3Nx0

in 2.1.0 i do not gert this error

**Comment by thedist** [comment]
It looks like the issue there is because vMix v22 doesn't support shortTitle property. This is something we can have a patch for in the next few days.

Because of vMix licensing it's not easy to test older versions of the software, so I can't give any assurance that there may not be other unsupported features that may also crash v22, but we'll try to fix what we can.

**Comment by zorangr** [comment]
I can do whatever testing you need
