### ISSUE TITLE
Add full bus control for inputs in StudioCoast vMix

### ISSUE THREAD

**Issue by mikesmithdudeman** [bitfocus/companion-module-studiocoast-vmix#76]
Currently, Companion has an action for the StudioCoast vMix module called: "vmix: Audio - Route input to Bus", and then the available fields are to type the input number/name/guid, and then to select from a drop-down list which audio bus (e.g. Master, A, B, C, etc) to route that designated input to.   

This is effectively a toggle; a relative change to the state; and does not allow you set an absolute state of the bus routing for each input.

I am requesting that you add a third field here which will allow you to select from a drop-down list, whether you want to "toggle" the bus's current state, turn it "on", or turn it "off".  I.E. add an absolute state assignment for the routing of each bus on the input.

The current action likely makes an API call which looks like:
"http://127.0.0.1:8088/api/?Function=AudioBus&Value=Bus%20B&Input=3"
This is the 'toggle'.

I'm asking for a drop-down to be added to not only be able to select this toggle, but also set (for example) Bus B "on" or "off" for a given input, which would look like:
"http://127.0.0.1:8088/api/?Function=AudioBusOn&Value=Bus%20B&Input=3"
and
"http://127.0.0.1:8088/api/?Function=AudioBusOff&Value=Bus%20B&Input=3"
respectively.

The use-case and need for this is probably pretty obvious, but one pressing example is to be able to create looks or presets with some or all of your callers who come in to the program at different times and in different combinations- so you need to be able to create presets or looks which route their audio to an audio Bus, on or off, regardless of what state it was previously in.

Thank you!

**Comment by McHauge** [comment]
This has now been added to the module and will be included in future releases, but you would not expect it in the beta's for at least a week or two.
