### ISSUE TITLE
Bus Status on remote instance

### ISSUE THREAD

**Issue by AttitudeVision** [bitfocus/companion-module-studiocoast-vmix#78]
I have been working on some programing in a local enviroment using an instance of Vmix @127.0.0.1

I have found that when moving to another machine where the http port had been changed some feedback instances (audio buses) did not work until returning them back to the default 8088. Is this expected behaviour as it is hard coded?  Would it be possible to change this so that the HTTP requests have a port number assigned as well?

**Comment by McHauge** [comment]
you will have to go into the instance and change the port under config for it to change, the default is set to 8080 if no other port is suplied

**Comment by McHauge** [comment]
@AttitudeVision We have switched over from the HTTP API to the TCP API, but the TCP port in vMix is locked internally, so that might be your problem.

**Comment by McHauge** [comment]
@AttitudeVision I have added a warning to the config page that explains this in versions going forward, to help prevent misunderstandings
