### ISSUE TITLE
Overlay to program stops working

### ISSUE THREAD

**Issue by loftdweller** [bitfocus/companion-module-studiocoast-vmix#80]
Hello all

I'm controlling a remote instance of Vmix (not in the cloud). 4K 23.0.0.67 via companion on a physical machine (Lenovo Legion)

Locally I have a Macbook Pro on mojave  w/ a stream deck XL. Companion V2 2.1.2

The overlay to program will work a few times, then stop. After pressing the button 5 times (it always seems to be 5 times) the overlay stops working. Any ideas?

Brian

**Comment by McHauge** [comment]
@loftdweller before looking too much at it, have you tried and tested if this is still occurring with the newest beta's.

These can be found by using the "builds" button underneath the main download button on the website.

**Comment by McHauge** [comment]
@loftdweller is this still a problem, I'll close this for now, but feel free to open it again, if it continues
