### ISSUE TITLE
Add feedbacks based on the sources of an inputs layers/multivew sources

### ISSUE THREAD

**Issue by sphlabs** [bitfocus/companion-module-studiocoast-vmix#87]
**Describe the feature**
Add feedback based on the current input being used as a specific layer in an(other) inputs multiview/layers.

**Is this version dependent (vMix v24.)?**
No

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc., to help the developers along.

**Usecases**
In concert with the ability to set the source for an inputs various layers, it would be useful to be able to display feedback based on the layers. e.g. Make background green when input 12 is set as layer 3 on input 2

**Comment by McHauge** [comment]
@thedist quick question, are you working on this currently?
