### ISSUE TITLE
Overlay Status Regardless of Input

### ISSUE THREAD

**Issue by tsvmitch** [bitfocus/companion-module-studiocoast-vmix#88]
**Describe the feature**
An instance feedback option for Overlay status, regardless of which input is in the overlay. The current feedback is input dependent.

**Is this version dependent (vMix v24.)?**
No

**Usecases**
After creating a page with buttons toggling different inputs into an overlay, you can then return to a main page for switching inputs behind the overlay. On the main page have a button indicating the overlay is on and allowing you to turn the overlay off, regardless of input.

**Comment by McHauge** [comment]
@tsvmitch just to verify, what you are requesting is a feedback like "Overlay Status" right, where it just shows if overlay 1-4 is on program/preview or not, like the 4 buttons over the t-bat in vMix. Is this the correct understanding?

**Comment by tsvmitch** [comment]
Exactly. It would be helpful so that we can have a separate page to set what is in the overlay, return to a main switching page, but still have an "overlay out" button that shows when the overlay is active, regardless of the current input.

**Comment by McHauge** [comment]
I'll give it a look tomorrow.  :)

**Comment by McHauge** [comment]
@tsvmitch hi, This is what I have added so far, and this should be available in the next update, expect it to be in the v2.2.0 betas in the coming week.
![image](https://user-images.githubusercontent.com/31018035/110595938-f61ead00-817e-11eb-9ea1-e5b68b86f79f.png)
