### ISSUE TITLE
How to have instance feedback of the AudioPluginOnOff function in Vmix?

### ISSUE THREAD

**Issue by LoganSulpizio** [bitfocus/companion-module-studiocoast-vmix#89]
Hi, 

If I'm not mistaken, it's not yet available to OnOff an AudioPlugin in Vmix with companion. I know that my application is quite specific and I understand it shouldn't be a priority. That's why I'm not requesting or suggesting it. My question is more about how could I get around that?
I've seen that the AudioPluginOnOff function can be triggered by the Vmix API via HTTP as explained in the Vmix website [here](https://www.vmix.com/help23/index.htm?DeveloperAPI.html). So, could anyone confirm that using the generic HTTP module of companion would actually work to trigger the AudioPluginOnOff function via the API?

Then, the problem becomes about the feedback. Any OnOff function is great but if you are not sure in which state you are in, it can be messy. Is there a way to go around that? Maybe there is a way to get the state of the plugin with the API? Could that be integrated in companion with a generic module to get the instance feedback at any time? How could I do it? Any ideas??

Thank you

**Comment by McHauge** [comment]
You can you the "custom command" to activate the command, but the feedback part would need specific integration in the module

**Comment by McHauge** [comment]
There is an explanation about how to use the custom command in the help file, it can be opened by clicking the  "?" Under instances

**Comment by LoganSulpizio** [comment]
Thank you for your help, I'll try it out.

Now, for the feedback, that means there is no way of getting the state of the function with a custom request or with the API?

**Comment by McHauge** [comment]
not in companion, that would require a change to the module itself, and you will need to have it compiled locally or by someone else.

**Comment by McHauge** [comment]
@LoganSulpizio hmm, just looked at the feedback part, and AudioPlugin OnOff is not exposed in the API, at least I can't find it, sorry. but I can add the action to the module for you.

**Comment by LoganSulpizio** [comment]
Thank you for your answer. I would surely use it if you add it to the module, but for now, I can manage something with the custom command, and it's fine. So it's ok.

Thanks to all of you, your work is really appreciated!

**Comment by stevespaw** [comment]
I was just getting ready to make this same request for Plug-in on and off :-) +1
I don't think the status is available which is a bummer. Feature request here:
[https://forums.vmix.com/posts/t25472-AudioPluginOn-in-Activators](url)

![image](https://user-images.githubusercontent.com/11045430/111000148-231dbc00-8347-11eb-8951-dbf7c66c718b.png)

**Comment by stevespaw** [comment]
If you add the AudioPluginShow we could at see status quickly for now.
Thanks a lot !
![image](https://user-images.githubusercontent.com/11045430/111000364-8a3b7080-8347-11eb-9fe5-bba2aa675b10.png)

**Comment by McHauge** [comment]
consider it added

**Comment by LoganSulpizio** [comment]
Thank you.
I've seen you released the version 1.2.17 on GitHub. How can I update the module in companion and have access to this latest version? When I start companion, I see the studiocoast-vmix module is still on 1.2.9?

**Comment by McHauge** [comment]
depends on what version of companion, for the GitHub release to match, you will need to be on the latest beta that should give you up to 1.2.16 as of today, as the 1.2.17 has not yet been pulled into the core

**Comment by LoganSulpizio** [comment]
OK, so no way to download the module updated and add it to companion?
Is the beta version available for anyone?

**Comment by McHauge** [comment]
only if you want to compile it yourself, otherwise you will have to use the premade builds, companion V3.0 aims to bring the support for adding/removing and updating modules on the fly, but that is ways ahead for now

**Comment by McHauge** [comment]
@LoganSulpizio the beta should now be up to date, if you download the newest build

**Comment by LoganSulpizio** [comment]
Ok, thank you for the update

**Comment by JeffInHighDef** [comment]
I am trying to open VST audio meters on screen with a Streamdeck. Does anyone know if this is possible? I have tried AudioPLuginShow, and a few others but have not seen it work. Thanks for any help.

**Comment by McHauge** [comment]
@JeffInHighDef Hi, can you show a picture of the button you have set up, and how many plugins do you have on the input?

**Comment by McHauge** [comment]
@JeffInHighDef At least for me this works using the action command: "Audio - Audio Plugin On/Off/Toggle/Show On Input" and selecting an input and what plugin and last the "show" action and not the "toggle" that it defaults to. since "toggle" toggles the plugin on/off.

**Comment by McHauge** [comment]
I'll close this for now, feel free to reopen this if you feel like it's still relevant
