### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion-module-studiocoast-vmix#90]
**Describe the bug**
Sentry is reporting a lot of errors with the line
https://github.com/bitfocus/companion-module-studiocoast-vmix/blob/master/src/tcp.js#L63

`RangeError: Invalid string length`

57k occurances from 6 users in roughly the last month.

**System (please complete the following information):**
 - Companion Version: multiple including 2.2.0-3e5a8eb-2868
 - vMix version [e.g. v23]

**Comment by McHauge** [comment]
someone must have some very bit setups

**Comment by Julusian** [comment]
or messageBuffer never ends with a `\r\n`.
This is plain tcp, so the data is treated as a stream of data and not packets. 
So if data is flowing often enough, then with bad luck the `\r\n` might always be in the middle of packets

**Comment by Julusian** [comment]
I think the correct fix here would be to do the append to messageBuffer. Then do a loop, looking for the next `\r\n` in that buffer, and repeating until there are no more

Something like
```
while(messageBuffer.length > 0) {
  const nextIndex = messageBuffer.indexOf(`\r\n`)
  if (nextIndex !== -1) {
    const msg = messaegeBuffer.slice(0, nextIndex)
    messageBuffer = messageBuffer.slice(nextIndex + 2)
    
    // process msg here
  } else {
    // no separator found
    break
  }
}

```

**Comment by McHauge** [comment]
@Julusian should I take it as this is something you can/will push a patch for.

**Comment by Julusian** [comment]
@McHauge sorry, I missed your reply to this
I can try and get to it, but Im not sure when that will be.

Ive just checked sentry, and there are ~1.6m entries for this across 36-43 users in the last 30 days.
