### ISSUE TITLE
StudioCoast vMix - Open Playlist not working

### ISSUE THREAD

**Issue by cookdoeyl** [bitfocus/companion-module-studiocoast-vmix#91]
The Open Playlist (or what vMix calls Select Playlist) command is not working with playlist name.

Comp: 2.1.2 (f4bcaf3-2679)
vMix: 23.0.0.67

**Comment by McHauge** [comment]
@cookdoeyl Hi, did you give this a try with the newest v2.2.0 beta there has been a lot of changes to this module since v2.1.2 released? and I think this got fixed when we did the URI encoding on commands

**Comment by cookdoeyl** [comment]
> @cookdoeyl Hi, did you give this a try with the newest v2.2.0 beta there has been a lot of changes to this module since v2.1.2 released? and I think this got fixed when we did the URI encoding on commands

I had not. I will try this tomorrow and check, but I do see in your release it was observed and fixed a few module revisions back. Didn't know the modules don't stay updated independently from Companion itself.

On a similar note (and this can be a different issue), is it possible to view the SelectedPlaylist as a feedback?

**Comment by McHauge** [comment]
I think that is already a part of the module in the v2.2.0 beta

**Comment by cookdoeyl** [comment]
I tried it on my personal computer. I see the Open Playlist has been fixed, however, I'm not seeing the Selected Playlist. There is a vMix input type called List with a selected index feedback, but that is different than the playlist function.

**Comment by McHauge** [comment]
@cookdoeyl  I think you are referring to the action "Playlist - Open Playlist" that is using the vMix shortcode => "SelectPlayList"
But unfortinally I can't see a way of making a feedback about it as it's not listed in the API.

**Comment by McHauge** [comment]
I'll close this, feel free to reopen if you still think its relevant
