### ISSUE TITLE
Stinger 3 and 4 not available for Vmix v24

### ISSUE THREAD

**Issue by pawellygan** [bitfocus/companion-module-studiocoast-vmix#95]
**Describe the bug**
Stinger 1
Stinger 2
ONLY on the list

**Expected behaviour**
Stinger 1
Stinger 2 
Stinger 3
Stinger 4 
on the list

**System (please complete the following information):**
 - Companion Version [e.g. 2.2.0 (70d5207-2717)]
 - vMix version V24.0.0.50

**Comment by McHauge** [comment]
@pawellygan they will be in the betas very soon :)

**Comment by pawellygan** [comment]
> @pawellygan they will be in the betas very soon :)

you think manually added 2 lines in the code will work temporarily?

**Comment by McHauge** [comment]
partly, depends on where, in actions, then yes, not sure about in feedbacks,

**Comment by pawellygan** [comment]
> partly, depends on where, in actions, then yes, not sure about in feedbacks,

gonna give it a try. For now don't care about feedbacks - just need to fire them ;)

**Comment by McHauge** [comment]
did not think that would close it, but they are now added, I also just tested it, both actions and feedback, I thought there would be a catch but that was quite simple :)

**Comment by pawellygan** [comment]
> did not think that would close it, but they are now added, I also just tested it, both actions and feedback, I thought there would be a catch but that was quite simple :)

Do you think the beta with this added will be available anytime soon?

**Comment by McHauge** [comment]
within a week normally, yes. properly in 1-3 days

**Comment by pawellygan** [comment]
looks like still, it hasn't been added

**Comment by McHauge** [comment]
@pawellygan they got included over 12 days ago, but you need to go ahead and download a new build of at least "companion-2.2.0-510598ee-3280" or newer for them to be there.

**Comment by pawellygan** [comment]
> @pawellygan they got included over 12 days ago, but you need to go ahead and download a new build of at least "companion-2.2.0-510598ee-3280" or newer for them to be there.

confirmed! Now it's there! Thx!
