### ISSUE TITLE
[Feature] Add Input Selection for LumaKey on Input.

### ISSUE THREAD

**Issue by TreborKutscher** [bitfocus/companion-module-studiocoast-vmix#99]
**Make a Actian that a allows to select the input used for LumaKey refernce on a input (ColorKey Menu Tab)
The Layout of this action should be the same as fpr the "Set Input as Multiview Overlay Layer" action, but ad NONE as selctelbe first item**
 
**not dependend on v24**

**Usecases**
Use a Black&White video as an lumakey source for inputs, to reaveal from dust etc.
Since in Mixes 2,3,4 videofiles won't play outomaicaly, an other vmix instance or other clipplayer is prefered either over input or NDI. But Everything can Crash so i want to hav a quick backup for all inputs wich are coupled with this lumakey input to switch to fallback white color source internally in vMix.

**Comment by McHauge** [comment]
@TreborKutscher Hi, I just looked through the available shortcodes in vMix v23 and v24, and am sad to say, I don't see a command that would execute that function. But if you can find it please let me know then I'll look at it.


Here is the list of vMix shortcodes:
[vMix Shortcodes](https://www.vmix.com/help24/ShortcutFunctionReference.html)

or give this tool a look though:
[vMix API Util](https://util.dist.dev/vmixapi)

**Comment by McHauge** [comment]
I might have spoken too early, there is the "SetAlpha" shortcode, I'll try it out later today

**Comment by TreborKutscher** [comment]
You are right, as i investigated the Shortcodes list, i only found the "SetAlpha" too but the selctor below is more intresting to me. But Setting the self alpha is also nice to have.
I will call this as a feature request in the vMix forums to implement this and further access to the keyer parameters via shortcodes.

**Comment by McHauge** [comment]
yes, it would be a nice addition to have in the list, to be able to change the lumakey on the fly, via shortcodes. I also made a request on the forum about the vmix call's when changing video source in the return channel. but post a link for your request so we can put in a "+1"
